### ISSUE TITLE
Create a page that provide an overview of all non context-specific data exports

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#103]
There should be one page where we can get to all data exports that are not tied to specific entity attachments. 

## Suggested solution

Create a custom page. The reason for is is. Maintaining a list like this by hand would be rather tricky as we keep adding/removing views/exports. Some custom code that output a block containing a list of them and their URL. We also need to think about displaying this list to non logged in users would not be very helpful then all the exports are.

## How to test

- Logg in to elmcip, only administrator users or users with the power to admin other users have access.
- Go to page https://test.elmcip.net/data to get a list of exportable views and their URL
- Logg out and verify that that the page give a no access.

**Comment by elmcip** [comment]
I guess we never rolled this out? This would be useful for students working on visualizations now.

**Comment by elmcip** [comment]
This works for now. But we should figure out permissions. Would there be a problem in making this available to all logged-in users? Would also be good to sort the page in some logical way, but I'm not sure best method.

**Comment by elmcip** [comment]
Let's look at how this can be useful to us in the next release focused on data exports. Should the page be structured in a particular way to make it more useful? Are permissions right?

**Comment by steinmb** [comment]
Closing this as it is. We have to revisit this in Drupal 9 - Current issues for this is found at https://github.com/smbjorklund/elmcip_config/issues/13
