### ISSUE TITLE
Automatic update test.elmcip.net to latest version of master branch

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#12]
Perhaps every night we update http://test.elmcip.net to the very latest dev. version.
- Reset site to production.
- Upgrade to latest version on master branch.
- Report on email if this breaks (might be belong in a separate issue).

**Comment by steinmb** [comment]
After we switch to a public repo, this got some easier. We do not have have a separate staging accounts. Changed all remote url test.elmcip.net from ssh to https, avoiding ssh keychain challenge. There is a cron job running site-upgrade on the master branch each 30 minute. A bit heavy handed, we should perhaps utilize git hooks and do nothing if nothing have been committed.

**Comment by AlvaroSeica** [comment]
Good, had gone thru milestone 1.27 and thought this was done!
