### ISSUE TITLE
Turn ELMCIP GitHub repository Public

### ISSUE THREAD

**Issue by AlvaroSeica** [elmcip/elmcip#120]
https://github.com/elmcip/elmcip should be public, so that users can insert bug and improvement issues.

* https://help.github.com/articles/making-a-private-repository-public/

**Comment by steinmb** [comment]
https://github.com/elmcip/elmcip is now public. Removed the ability to create wiki. Revoked all collaborators except me and @AlvaroSeica

Someone should also write an article on elmcip.net about this, not only on social media.

**Comment by elmcip** [comment]
Hmmm — I don’t seem to, but must have under a different login. I remember about a year or so ago we were trying to track down the email settings on Google. 
-----------
Scott Rettberg, Professor of Digital Culture, University of Bergen

http://crchange.net <http://crchange.net/> CRchange projects
http://elmcip.net/knowledgebase <http://elmcip.net/knowledgebase> ELMCIP Electronic Literature Knowledge Base
http://retts.net <http://retts.net/>

**Comment by elmcip** [comment]
I can do the book of faces. We could also put something on our research group site (also good to remind people about ELMCIP).


-----------
Scott Rettberg, Professor of Digital Culture, University of Bergen

http://crchange.net <http://crchange.net/> CRchange projects
http://elmcip.net/knowledgebase <http://elmcip.net/knowledgebase> ELMCIP Electronic Literature Knowledge Base
http://retts.net <http://retts.net/>

**Comment by AlvaroSeica** [comment]
@steinmb @elmcip https://elmcip.net/story/elmcip-github
FP is good to go! Anything else I should add? Good to go on Twitter?
@elmcip can you post on https://www.facebook.com/groups/ELMCIP.knowledge.base/ and BEL UiB site (or Jill)?

**Comment by steinmb** [comment]
In https://elmcip.net/story/elmcip-github - there is this line that I did not understand

>You will find more info on how to contribute in the front page.

In https://elmcip.net/story/elmcip-github I added a link to my blog post about the change and the elmcip project - https://smbjorklund.no/elmcip-now-public-project-github
