### ISSUE TITLE
Other edition field does not display on critical writing records

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#174]
The links to the "other edition"s should appear on the left sidebar box of the critical writing records.

**Comment by hannahackermans** [comment]
Heey, we solved this at some point apparently, but the “other edition” is not showing in view in critical writing records again.

**Comment by steinmb** [comment]
Re-reading the issue. Not sure we fixed anything. It still have quite few open questions and I see no proof of us agreeing on anything. Perhaps this was discussed in a ELMCIP meeting? Feel free to re-open the issue and move milestone to next release.
