### ISSUE TITLE
Change PO.EX field label and link title

### ISSUE THREAD

**Issue by AlvaroSeica** [elmcip/elmcip#191]
Spin-off from #132

- Content type: Critical Writing
- Field Type: ELD entry and PO.EX entry (it is under "References and Attachments")
- Field Label: "Electronic Literature Directory entry". Change: "<b>See also:</b> Electronic Literature Directory entry"
- Field Label: "Po.Ex entry: Po.Ex record". Change: "<b>See also:</b> Po-ex.net entry"

<img width="962" alt="exploratory_programming_for_the_arts_and_humanities___elmcip" src="https://cloud.githubusercontent.com/assets/6121438/15179009/7ebe4762-1779-11e6-94c5-5401ee202ad4.png">

- Field Label: "Po.Ex entry". Change hardcode: "Po-ex.net entry"
- Change Box into Multiple Box Field

![edit_critical_writing_sensing_exigence__a_rhetoric_for_smart_objects___elmcip](https://cloud.githubusercontent.com/assets/6121438/14888883/8f00a13c-0d5c-11e6-97a8-444898468636.png)

**Comment by steinmb** [comment]
No feedback. I think we are done here. Closing
