### ISSUE TITLE
Field help text review

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#224]
We should review and as necessary edit all field help text descriptions thoroughly. This is mainly an editorial task, but we should check through all of them and make changes to improve clarity and eliminate outdated information.

## Content types

- [x] Create Creative Work
- [x] Create Critical Writing
- [x] Create Person
- [x] Create Platform/Software
- [x] Create Teaching Resource
- [x] Create Publisher
- [x] Create Organizations
- [x] Create Event
- [x] Create Databases and Archives
- [x] Create Research Collection

**Comment by hannahackermans** [comment]
When I was testing the links of the field help texts ( #343 ). I realized we have two field help texts in Create Databases and Archives that are missing the add-links altogether, in the references and attachment-section.
![screenshot-2017-10-17 create databases and archives elmcip](https://user-images.githubusercontent.com/18713442/31667445-c60ee202-b34f-11e7-8de5-df6aec2306c6.png)

I don't know if we had a special reason for doing it this way, but I think we should change these two field help texts to include add-links. 

So, I think it should be: 
Events
"If the database or archive has been featured at an event, link to it here. The event will autocomplete if it is in the database. If the event is not yet in the database, add the event."

Critical Writing
"If the database was featured in a critical writing, link to it here.  The critical writing will autocomplete if it is in the database. If the critical writing is not yet in the database, add the critical writing."

**Comment by steinmb** [comment]
@hannahackermans Agree. Let just update the help text.

**Comment by steinmb** [comment]
>Events
>"If the database or archive has been featured at an event, link to it here. The event will autocomplete if it is in the database. If the event is not yet in the database, add the event."
>
>Critical Writing
>"If the database was featured in a critical writing, link to it here. The critical writing will autocomplete if it is in the database. If the critical writing is not yet in the database, add the critical writing."

Should soon be ready staged on test and ready for review.

commit 2e52f16395533a18506c2d0e13714fb8224263df (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Nov 13 17:29:01 2017 +0100

    Issue 224 Improved Databases and Archives field help text

    Events and Critical Writing was added information how to add
    nodes if they is not there.

**Comment by steinmb** [comment]
Closing. Re-open if there is anything missing.
