### ISSUE TITLE
Platform - remove promoted to front page status from a set of nodes 

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#269]
Someone with permission have tagged a set of nodes as published to front page. Not sure if this is in on purpose. As far as I know do we not use this node tag in any of the content listings.

## Suggested fix

* [x] Remove published to front page
* [x] Remove https://elmcip.net/node
* [ ] Audit permissions to use this on KB content.

## How to test

* Only story content types should have the `promote` and `sticky` option on both create new and edit existing.
* Users with access to `/admin/content` should not have the option to demote, promote, sticky and unsticky.

### Content overview page - Before change

![fullscreen_12_09_2017__12_57](https://user-images.githubusercontent.com/683617/30322549-1eee0f6c-97ba-11e7-9b48-514457382ca5.png)

### Content overview page - After change

![fullscreen_12_09_2017__12_59](https://user-images.githubusercontent.com/683617/30322586-45f39b90-97ba-11e7-99ca-c1ee5803a241.png)

## Nodes updated

    SELECT nid, title, type FROM node WHERE promote = 1 AND type != 'story';
    
    +-------+----------------------------------+-------------------+
    | nid   | title                            | type              |
    +-------+----------------------------------+-------------------+
    |  9970 | Processing                       | platform_software |
    | 10254 | Linux                            | platform_software |
    | 10255 | Cascading Style Sheets (CSS)     | platform_software |
    | 10256 | Flash                            | platform_software |
    | 10257 | PHP                              | platform_software |
    | 10258 | JavaScript                       | platform_software |
    | 10259 | Java                             | platform_software |
    | 10260 | Mac OS X                         | platform_software |
    | 10261 | PlayStation                      | platform_software |
    | 10263 | The Wii                          | platform_software |
    | 10265 | BASIC                            | platform_software |
    | 10267 | Extensible Markup Language (XML) | platform_software |
    | 10268 | BlueJ                            | platform_software |
    | 10277 | Commodore 64                     | platform_software |
    | 10278 | Twine                            | platform_software |
    | 10279 | Gameboy                          | platform_software |
    | 10280 | MySQL                            | platform_software |
    | 10281 | jQuery                           | platform_software |
    | 10282 | Amiga                            | platform_software |
    | 10283 | Xbox                             | platform_software |
    | 10284 | StorySpace                       | platform_software |
    | 10285 | Blender                          | platform_software |
    | 10296 | ALGOL                            | platform_software |
    | 10297 | Ruby                             | platform_software |
    | 10298 | Drupal                           | platform_software |
    | 10299 | Python                           | platform_software |
    | 10300 | Google Chrome                    | platform_software |
    | 10301 | DSpace                           | platform_software |
    | 10302 | Netscape                         | platform_software |
    | 10303 | ZX Spectrum                      | platform_software |
    | 10304 | WordPress                        | platform_software |
    | 10305 | FORTRAN                          | platform_software |
    | 10306 | Internet Explorer                | platform_software |
    | 10307 | SCALAR                           | platform_software |
    | 10308 | Shockwave                        | platform_software |
    | 10309 | Ebay                             | platform_software |
    | 10310 | Facebook                         | platform_software |
    | 10311 | HyperCard                        | platform_software |
    | 10312 | Apple 2                          | platform_software |
    | 10313 | RiTa                             | platform_software |
    | 10314 | Squeak                           | platform_software |
    | 10315 | iPhone                           | platform_software |
    | 10316 | Google Earth                     | platform_software |
    | 10317 | Spatterlight                     | platform_software |
    | 10318 | Twitter                          | platform_software |
    | 10319 | Vimeo                            | platform_software |
    | 10320 | C++                              | platform_software |
    | 10321 | Google Maps                      | platform_software |
    | 10322 | Open StreetMap                   | platform_software |
    | 10323 | iPad                             | platform_software |
    | 10324 | YouTube                          | platform_software |
    | 10325 | Layar                            | platform_software |
    | 10327 | Android                          | platform_software |
    | 10328 | DHTML                            | platform_software |
    | 10329 | Atari                            | platform_software |
    | 10361 | iTunes                           | platform_software |
    | 10362 | Quicktime                        | platform_software |
    | 10364 | Instagram                        | platform_software |
    +-------+----------------------------------+-------------------+
    58 rows in set (0.00 sec)

**Comment by steinmb** [comment]
One down.

commit 9e54051251cbf65921deb5b010800e0a2c251cd0
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Tue Sep 12 11:30:33 2017 +0200

    Issue 269 - Remove /node and change news path to /news

    Drupal comes with a default front page example.com/node. ELMCIP
    uses another front page. ELMCIP also uses a view that pulls out
    the nodes that is "promoted" to front page (views_recent_posts)
    that create a short list on the front page + exposes all story
    types, promoted or not.

    This remove /node and changes news to /news to prepare us to remove
    the block from front page and replace it with a menu link.

**Comment by steinmb** [comment]
@AlvaroSeica this is the last task in this issue. Remove promote and sticky to all add or edit nodes except for `Story`.

Note: To make sure they cannot be turned on by going to `/admin/content`, administrative editor are allowed. I had to remove: demote, promote, sticky and unsticky. Here I had to remove it for all content types. These are batch options in a single list. No other way. This can completely removed in the future if we end up not liking this bit of the change.

### Content overview page - Before change

![fullscreen_12_09_2017__12_57](https://user-images.githubusercontent.com/683617/30322549-1eee0f6c-97ba-11e7-9b48-514457382ca5.png)

### Content overview page - After change

![fullscreen_12_09_2017__12_59](https://user-images.githubusercontent.com/683617/30322586-45f39b90-97ba-11e7-99ca-c1ee5803a241.png)


ommit 935b41b86a92e9d627b0b2b733ed128eb271ef38
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Tue Sep 12 13:08:08 2017 +0200

    Issue 269 Remove promote and sticky from all except story

    Confuse some users with the power of to promote articles and we should
    also make sure we do not populate nodes with properties we should not
    have.

    Also remove this option from the content overview page for the users
    to access it.

**Comment by elmcip** [comment]
Is there a reason this issue is open?

**Comment by steinmb** [comment]
Checking..... No, I fixed it back in sept. Good catch.
