### ISSUE TITLE
Narrabase entry 

### ISSUE THREAD

**Issue by hannahackermans** [elmcip/elmcip#281]
When entering a URL in the field of "Narrabase.net" in creative writing, two issues come up in viewing the saved page.

1) Narrabase.net was previous called "authoring software" and this is still the name in view. 
<img width="603" alt="screenshot 2016-11-18 11 10 29" src="https://cloud.githubusercontent.com/assets/18713442/20426637/5392bd00-ad80-11e6-94bd-05e6427b7de9.png">
<img width="551" alt="screenshot 2016-11-18 11 13 07" src="https://cloud.githubusercontent.com/assets/18713442/20426638/5392ef5a-ad80-11e6-97ce-92757d7373b3.png">

2) As you can see above, the name repeats "see also", which in all other fields is said as text, and in the narrabase entry also as part of the hyperlink

**Comment by elmcip** [comment]
We should fix this, should be a quick fix in field definition.
