### ISSUE TITLE
Worldcat hyperlink 

### ISSUE THREAD

**Issue by hannahackermans** [elmcip/elmcip#283]
In adding URLs to creative works, almost all fields turn the "title" of the URL into a hyperlink in view.

In the case of Worldcat, however, the title and the URL appear underneath each other. 

Is it possible to make the same hyperlink for the Worldcat entry?

<img width="225" alt="screenshot 2016-11-18 11 28 27" src="https://cloud.githubusercontent.com/assets/18713442/20427084/7c8a8538-ad82-11e6-8d46-93711b21d5c6.png">

**Comment by hannahackermans** [comment]
Hi @steinmb , it looks like the title (year) and the URL are displaying underneath each other again. 
Can you make sure it becomes a hyperlink again? I think that looks cleaner than displaying the URL. 

<img width="219" alt="worldcat screenshot" src="https://user-images.githubusercontent.com/18713442/64957899-3bb23080-d88e-11e9-8090-fbce9877909c.png">
(screenshot of https://elmcip.net/node/14469)

**Comment by steinmb** [comment]
Good catch. You are right. It was changed back in 2017 by issue #339 in this commit:

commit f7998a0ccd1ca5f242e09befdc21ff6ee5231d09
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Aug 23 16:50:55 2017 +0200

    Issue 339 Critical-writing remove view modes and add meta data wrapper

    See issue 242 for details.


I have reverted this change and it should be OK now

commit b8a433a71afd11d2d7fb4aefb659f2d28b9fea3e (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Tue Sep 24 11:24:39 2019 +0200

    Issue 283 Use title as link in WorldCat link field

    Addresses change introduced by cleanup issue #339

**Comment by elmcip** [comment]
Works on test.
