### ISSUE TITLE
Upgrade theme to HTML5 and mobile first

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#300]
The current theme and base theme have the same layout system as we had back in Drupal 6 days. When we upgraded we stayed at the same base theme to ease the upgrade pain. Though we never kept up with the emerging "new" and cool thing as mobile/table thingies.

## Suggested fix

* Move to Bootstrap 3.
* ~~Move away from Zen 7.x.3 to Zen 7.x.6 - Suggest we keep Zen as a base theme. It is quite good - https://www.drupal.org/project/zen~~
* Design move to a "mobile first" responsive and fluid layout. Allowing us to scale properly from small to high res screens.
* HTML "5"
* Move away from CSS and into SASS system.
* ~~Get proper live style guide based on processed live SASS/CSS -files.~~

**Comment by steinmb** [comment]
619c93ae (HEAD -> issue_300-new-theme, origin/issue_300-new-theme) Alter symlink enable us to have multiple elmcip themes
77ba2b83 Updated Zen theme to 7.x-6.x branch
61e022e (HEAD -> issue_300) Issue 300 moved preprocess function from old theme.
a9c6e63 (origin/issue_300) Issue 300 Updated theme name
d078e97 issue 300 Added new theme starterkit
07ca546 Move elmcip theme to elmcip_old theme

**Comment by AlvaroSeica** [comment]
So @steinmb it cannot be testes yet right?

**Comment by steinmb** [comment]
Sorry, nothing to test yet.

**Comment by steinmb** [comment]
We have separate issues to address before we roll this. 

Example. The footer section of the site need to be improved. New layout method for the sponsor block, move some of the menu links we have in header would fit better in the footer.

**Comment by steinmb** [comment]
Machine vision exposed a weakness in our setup. Addressed in:

commit 86ba93a4efd67282ad4259c7e2326755706c8339 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon May 27 13:46:55 2019 +0200

    Issue 300 Allow us to have multiple custom themes

    New symlink

commit 16ab2f28f14b09efc2f23d208205f0766256eef7
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon May 27 13:44:11 2019 +0200

    Issue 300 Allow us to have multiple custom themes

    Change the symlinks to dir not theme.

**Comment by steinmb** [comment]
Postponing on issue #439

**Comment by steinmb** [comment]
Outdated, closing
