### ISSUE TITLE
search_api_db_update_7107 fail to run on upgrade

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#310]
```Cannot change the definition of field search_api_db_default_node_index_text.field_name: field doesn't exist.```

Fail to upgrade to latest version.

## How to fix

Remove config, server, index(es), views from Feature module.

## How to test
No end user testing req.

**Comment by steinmb** [comment]
Search API server and index does not play nice with Features. When site with config get reverted on staging, odd stuff might happen (example in [issue 1347438](https://www.drupal.org/node/1347438). 

Our stored configuration and live data do no longer correlate and this causes unexpected behavior when hook_update_N() run. We could try to lock down the features with `features_feature_lock()` though by doing that we might just as well remove it from Feature at all since it blocks us from pushing and reverting new changes to running site.

These changes remove almost all config. We loose the search backend though I have added an new search db (SQL) to the live site. Going to let backup run, and re-test this tomorrow.

commit 16ea8e5b569c653acc666e3175315be38a173461 (HEAD -> issue_310, origin/issue_310)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Oct 26 13:01:04 2017 +0200

    Issue 310 Change search index backend.

commit c72caff69985ef51fe41d1458f56e62babcb7bd9
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Oct 26 12:08:58 2017 +0200

    Issue 310 Remove index, solr and view from feature

**Comment by steinmb** [comment]
These one is a little tricky and we need to be careful when staging this in production. Pushing to master and re-test on beta.elmcip.net. We have to switch search api backend after this, re-build the index and re-create a search page.

**Comment by AlvaroSeica** [comment]
yes, need me to do something?

**Comment by steinmb** [comment]
@AlvaroSeica No. This is a tricky one. This commit is the last piece of puzzle we need.

## This works

Verified this on beta.elmcip.net - Manual roll to get the config out of this situation.

```
git co production
git submodule update
drush sql-drop beta
Do you really want to drop all tables in the database betaelmcip? (y/n): y
gunzip -c $HOME/latest.elmcip.sql.gz | bin/site-drush sql-cli
git co master
git pull
git submodule update
```

Then we need to use search API UI and alter the config. 
* Switch index backend.
* Disable search page
* Disable old search backend server.
* Remove disabled db backend. This also flush old pending Solr db from the system.
* Enable search page
* Re-index everything

```
bin/site-upgrade master
 Elmcip_setup   7059  Uninstall Taxonomy Manager module.
 Search_api_db  7107  Eliminates the use of low-standard hashes.
 Performed update: search_api_db_update_7107                                                                                                                               
 Performed update: elmcip_setup_update_7059
```

That should be "all".

commit 5a16b37ae053cebef144c8179098ea21c87cf707 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Sat Nov 11 14:08:13 2017 +0100

    Module update and issue 315 search_api_db 7.x-1.6

        https://www.drupal.org/project/search_api_db/releases/7.x-1.6

**Comment by AlvaroSeica** [comment]
Then is it fine to move to the next milestone, I guess?
