### ISSUE TITLE
Knowledge base updated date-time standard formatting

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#323]
When we lists content and expose the "last updated" or post time we do this different ways. Sometime show date, sometime date and time with 12h or 24h format.

## Views listing dates

* http://elmcip.net/work
* http://elmcip.net/research_collections
* http://elmcip.net/author
* http://elmcip.net/data/platform
* http://elmcip.net/teaching_resource
* http://elmcip.net/organization
* http://elmcip.net/event
* http://elmcip.net/db_archives

## Suggested fix

Only show date and year in this format: `day.month.year` Example: `28.10.1970`

## How to test

Navigate views listed above. Compare to production.

**Comment by elmcip** [comment]
Author block on front page now displays the time -- we only need date.

**Comment by elmcip** [comment]
We agree that date style should be 28.10.1970.

Hannah will check for places where it is not in this format.

**Comment by steinmb** [comment]
Updated Author. That change is going in the 1.31 relase

commit 01002ef6107bbc87325010562fe151c770a1cbc8 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Sep 6 14:27:17 2019 +0200

    Issue 323 Do not expose time from view Author_page and cleanup

    - We do not need to expose time to visitors though we sort on time and date
    - Removed short edit links from KB front page. Reduce clutter
    - Fixed incorrect sort settings on KB block and page.
      - Block sort by last update, removed all other sorting options
      - Author page sort by last name and enable all other sorts.
    - Security improvements. View use general view content permission.

**Comment by elmcip** [comment]
It still needs to be fixed on Databases and Archives. Otherwise all good.

**Comment by steinmb** [comment]
commit d9772edf1e0e3050e2a6b810249058a6d63bcc2a (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Jan 29 17:45:12 2020 +0100

    Issue 323 Databases and Archives page date formatting

    Updated both page and block formatter to use: d.m.y
