### ISSUE TITLE
Improve layout in Databases and Archives and remove unused view modes and config

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#338]
Details found in meta issue #242.

## Scope

Make sure that all fields that we can populate are correctly positioned. Text, views, images, files and so on.

### Teaser mode

![databases_and_archives___elmcip](https://user-images.githubusercontent.com/683617/29615243-6b79eb42-880d-11e7-96cf-441138761d06.png)

### Full node view
![databases_and_archives___elmcip](https://user-images.githubusercontent.com/683617/29615224-5969fcbc-880d-11e7-81c7-36fa9ee2e8c5.png)

## How to test

* The scope is to make all elements in content type position more and less correctly. Flush out any `special CSS`, configs etc.
* Load different org nodes. Take a good look. Try to spot page elements that seems out of place.
* Populate all fields,  some fields, multiple data into same field. Se if you are able to break layout or make it look really bad.
* Create new one and test.

**Comment by AlvaroSeica** [comment]
Shall I review this after we also correct the Tags position? See caption:

(node/9993)

<img width="483" alt="compart_dada__the_database_digital_art___elmcip" src="https://user-images.githubusercontent.com/6121438/32898493-966cfe70-cae8-11e7-8df8-12d81520add7.png">

**Comment by steinmb** [comment]
Agree, that does not look correct. Good catch.

**Comment by steinmb** [comment]
These two changes should address the findings above.

commit df582b808c972ad1c43e2193467a64e0448a257f (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Apr 18 18:33:28 2018 +0100

    Issue 338 Left node sidebar content type header

commit 036984abed7e53c4aeee959e904325b7a9b3b346
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Apr 18 18:05:46 2018 +0100

    Issue 338 improve field labels and tags layout

    Follow up issues discovered during reviews of issue 338.
