### ISSUE TITLE
Term name and term id order is incorrect in in creative work export

### ISSUE THREAD

**Issue by AlvaroSeica** [elmcip/elmcip#354]
Term name and term id does not match up in the data export. One the the have to be in the wrong order.

## Fix 

It was the taxonomy term name that came out in the wrong order, not the term id. Removed the field from display: Master, block, page and Data export and added the one used for term id.

## Data structure

* View: Work
* field: Content: All taxonomy terms
* Display: Master, block, page and Data export.
* Test node: SpeidiShow - Node ID 10052
* Validate term id: `https://elmcip.net/taxonomy/term/<term id>`

## Before fix

Node ID 10052

`https://elmcip.net/taxonomy/term/<term id>`

Term title                  |    Term ID
------------------ | ---------------- 
creative language | 1952
imaginary TV show | 163
livetweeting | 4841
network improve narrative | 242
reality tv | 552
sharingplatform | 4842
transmedia narrative | 6051
collective narrative | 6052
fragmentation | 4640
game | 1817
hoax | 608
netprov | 6835
social networks | 8167

## After fix

Term title                  |    Term ID
------------------ | ----------------
netprov | 1952
collective narrative | 163
reality tv | 4841
hoax | 242
social networks | 552
network improve narrative | 4842
livetweeting | 6051
imaginary TV show | 6052
transmedia narrative | 4640
fragmentation | 1817
game | 608
creative language | 6835
sharingplatform	| 8167

## How to test

* Compare export in [live site](https://elmcip.net/work?title_2=&title_3=SpeidiShow&field_language_tax_tid=All&field_work_year_value_op=between&field_work_year_value%5Bvalue%5D%5Bdate%5D=&field_work_year_value%5Bmin%5D%5Bdate%5D=&field_work_year_value%5Bmax%5D%5Bdate%5D=&title=&title_4=&title_1=&taxonomy_vocabulary_1_tid=) with the [test site](https://test.elmcip.net/work?title_2=&title_3=SpeidiShow&field_language_tax_tid=All&field_work_year_value_op=between&field_work_year_value%5Bvalue%5D%5Bdate%5D=&field_work_year_value%5Bmin%5D%5Bdate%5D=&field_work_year_value%5Bmax%5D%5Bdate%5D=&title=&title_4=&title_1=&taxonomy_vocabulary_1_tid=) and validate that it is OK.

## Original report

@steinmb here's an example: downloading XLS tables with any content filtered from elmcip.net/work

querying the db for platform=instagram, returns 4 hits:
https://elmcip.net/work/%2A?title_2=&title_3=&field_language_tax_tid=All&field_work_year_value_op=between&field_work_year_value%5Bvalue%5D%5Bdate%5D=&field_work_year_value%5Bmin%5D%5Bdate%5D=&field_work_year_value%5Bmax%5D%5Bdate%5D=&title=&title_4=&title_1=instagram&taxonomy_vocabulary_1_tid=

now, the XLS exported has the problem of not pulling the right order of tags:

<img width="1414" alt="workbook7" src="https://user-images.githubusercontent.com/6121438/32628405-08165b32-c596-11e7-9648-341e77d979a9.png">

The Tag ID 1952 should correspond to "creative language", but it does not, in fact, it is "netprov".
https://elmcip.net/knowledgebase/all_tags_frequency/1952?type_1=All

**Comment by steinmb** [comment]
Interesting stuff :wow Going to have a look at it today.


### SpeidiShow - Node ID 10052

`https://elmcip.net/taxonomy/term/<term id>`

Term title                  |    Term ID
------------------ | ---------------- 
creative language | 1952
imaginary TV show | 163
livetweeting | 4841
network improve narrative | 242
reality tv | 552
sharingplatform | 4842
transmedia narrative | 6051
collective narrative | 6052
fragmentation | 4640
game | 1817
hoax | 608
netprov | 6835
social networks | 8167

**Comment by AlvaroSeica** [comment]
Brilliant! Thanks

**Comment by steinmb** [comment]
This should be right. Upgraded the issue with information on how to test it.

commit ebec22304b1c527fafd5260d63971dcaf9516aaa (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Nov 10 12:03:09 2017 +0100

    Issue 354 term name and id from views order do not match

    Removed "All taxonomy terms" from all display and re-added
    the one used by term id.

**Comment by AlvaroSeica** [comment]
Thxs, want me to test on test.elmcip?

**Comment by AlvaroSeica** [comment]
Ok got your edit on top now, will test

**Comment by AlvaroSeica** [comment]
@steinmb thanks a bunch, solved the mistery, in fact it was the taxonomy terms order. It is working good now. Can you roll a new version or do you want me to give you a quick feedback on something else so that you roll more issues? Students need this urgently though.
