### ISSUE TITLE
Improve view critical writing publisher data export

### ISSUE THREAD

**Issue by AlvaroSeica** [elmcip/elmcip#355]
@elmcip @steinmb can one of you asap create an export for a student (the only one working with EBR, 16 others working with platform and tags in final stage, hence issue #354) for EBR with:

https://elmcip.net/publisher/ebr-electronic-book-review

Content published with article+series (appears in)+tags from that article. 

That's infor that should be pulled here, but it does not:
https://elmcip.net/critical_writing?field_language_tax_tid=All&field_pubtype_tax_tid=All&title=ebr

**Comment by steinmb** [comment]
Let me see if I can understand this issue.

* First off. Should we improve https://elmcip.net/critical_writing or do we need to make a new view?
* This is a example of a export from https://elmcip.net/critical_writing - What data is not there that should be there?

Title | Nid | Author | Author ID | Year | Publication Type | Publication Type ID | Publisher | Publisher ID | Appears in | Journal NID | Tags
------ | ------ | --------- | ----------- | ------- | ------------------- | --------------------- | ----------- | -------------- | ----------- | -------------| ------
Vectora l Muscle in a Great Field of Process | 12722 | Yves Abrioux	| 1585 | 2004 | Article in an online journal | 20001588 | ebr Electronic Book Review | 127 | Critical Ecologies | [field_inbook_1-nid] | deleuze, Gilles Deleuze, bergson, mcelroy, Varela, Francisco Varela, butor, michel butor, yves abrioux

**Comment by AlvaroSeica** [comment]
So, I think it just needs to me improved. "Appears in" is good, but then its NID should appear in Journal NID: https://elmcip.net/critical-writing/critical-ecologies (in this case it is a series, but it "critical writing" content-type.
Then, Tags are good, but we need another column pulling Tags ID.

**Comment by steinmb** [comment]
OK so we fix `Journal NID` add a `Tags ID` —field to the existing view.

>So, a case like https://elmcip.net/critical-writing/critical-ecologies which is a series shoud be pulled as Journal NID--it is "critical writing" content-type.

Could you please elaborate a little more? I did not quite follow you.

**Comment by AlvaroSeica** [comment]
Yes let’s fix both. My point is: if JOURNAL ID is pulling those specific NIDs of “appears in” then it’s correct :)

**Comment by steinmb** [comment]
Brilliant. Let us try this then :)

**Comment by steinmb** [comment]
Here is a start and example on export: 
[critical_writing_2017-11-11T16-45-35.xls.zip](https://github.com/elmcip/elmcip/files/1463844/critical_writing_2017-11-11T16-45-35.xls.zip)


commit b895b8b7201ab40667eba613c200c850da551377 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Sat Nov 11 16:42:31 2017 +0100

    Issue 355 Fix journal nid rewrite, add term id to CW view

    Improve data export in view critical writing
    Journal node id re-write was broken. Added new field
    exposing tags (term) ID.

**Comment by AlvaroSeica** [comment]
This is great, working perfectly! Also, tested by filtering language and pub type and its exporting with Journal ID and Tag ID: https://test.elmcip.net/critical_writing 👍

**Comment by steinmb** [comment]
I'll try and roll a new release today then
