### ISSUE TITLE
Improve page footer section

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#356]
Improve the footer. It really need some TLC. Nothing fancy. Fix a few low hanging fruits but it will improve the look and able us to alter page width of the site and so on. Related to issue #300 and #352.

## Scope

<img width="977" alt="elmcip_v1_26_released___elmcip_-__private_browsing_" src="https://user-images.githubusercontent.com/683617/32737055-52a0f8dc-c899-11e7-9037-d981faf249af.png">

* [x] Sponsor list should change from one big ass image mapped with image map. Tried to increase the width of the page and it just made it look even more silly.
* [x] By improving the footer, some of the menu links from the header could be moved down. Simplifying but header. It could also enable us to reduce the real estate occupied by the header section. Giving us more space to the real content.
* [x] Add section that allow us to store menu links to more static pages.

## How to test
TBD

**Comment by AlvaroSeica** [comment]
I agree, all in one line works better, and def. reducing the size of BEL.

**Comment by steinmb** [comment]
Starting point but I need separate images of the sponsors. Ideally transparent png files.

commit 1131b12a286d6936265b8d21c50c394a3b29476b (HEAD -> issue_356, origin/issue_356)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Dec 7 16:15:59 2018 +0100

    Issue 356 Create new footer section

    Directly in page footer render list of sponsors
    remove the outdated and hard to maintain map image.

**Comment by steinmb** [comment]
@hannahackermans since I am pressed for time. Any change you could assist me on getting hold of the logos so we could re-create the page footer section?

**Comment by elmcip** [comment]
BEL Logos: https://www.dropbox.com/sh/yjiwwjumq0oxkm6/AACMwoI104GPCIZG_3c_9ukua?dl=0

**Comment by elmcip** [comment]
ELMCIP logos: https://www.dropbox.com/sh/1x74l8mpngtj450/AABbeNhRDMYFpPgF1POHi_sya?dl=0

**Comment by elmcip** [comment]
European Commission: https://www.dropbox.com/sh/rozvpyuptwktthh/AACoGXk2msibLaTM5LifyvCsa?dl=0

**Comment by elmcip** [comment]
UiB logos: https://www.dropbox.com/sh/jiezc2fvqwv0149/AACv83qTSDcNQOrDYYD0vbVza?dl=0

**Comment by hannahackermans** [comment]
Here are the transparent logos of Clarino (in their new colors!), UiB, and European Commission. 
I guess the BEL does not need to be transparent if we use the one with the black background. 
I have emailed HERA, I will let you know when they respond. 
and that's all the logos we need, right? (because we don't need 7th framework programme and Norstore anymore)

![Clarino](https://user-images.githubusercontent.com/18713442/59593355-0f9ddc80-90f2-11e9-9b93-24b45699c4e0.png)
![uib-ugle_transparent](https://user-images.githubusercontent.com/18713442/59593356-0f9ddc80-90f2-11e9-8983-889af8088dd3.png)
![European_Commission svg](https://user-images.githubusercontent.com/18713442/59593469-4f64c400-90f2-11e9-88a1-2b048eed6fb1.png)

**Comment by hannahackermans** [comment]
and here's HERA
![HERA White Logo on Black](https://user-images.githubusercontent.com/18713442/59672714-493d1900-91c0-11e9-960c-98824a520aee.png)

**Comment by steinmb** [comment]
Blowing through this issue. Here is a updated list. Did we miss anyone?

![Screen Shot 2019-08-23 at 18 46 51](https://user-images.githubusercontent.com/683617/63609022-882f8680-c5d6-11e9-9db8-8e5a4cc20dbd.png)

**Comment by steinmb** [comment]
cbc05fd Issue 356 Optimize image sizes
7991615 Issue 356 Include sponsor block css
514647e Issue 356 Sponsor images with own class
5250e1c Issue 356 Add all logos to elmcip_setup module
9db82a5 Issue 356 Swap out old markup
3f5872f Issue 356 Do not hard code sponsor block in the site theme
9cdbb31 Issue 356 Create new footer section
dc4184b Issue 356 Micro-optimization, no reason to assign before returning
8ba0561 Issue 356 Rewrite to PHP array short nested style
7ee4c5e Issue 356 Do not hard code theme path
f95223e Issue 356 We do not need to render the block content
6fa0d14 Issue 356 Restructure code. Moved block definitions to separate file
bd51988 Issue 356 Convert to PHP array short style
