### ISSUE TITLE
Email not working / Mollom error?

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#359]
Received feedback that the web form on the site is not woking, and notice that there is an error message on the status of Mollom API keys -- possibly related to move to a new server? I'm not sure if the system is sending mail either?

**Comment by elmcip** [comment]
Just got a second email on this. Can we prioritize a fix on the spam filter asap?

**Comment by elmcip** [comment]
I temporarily changed the Mollom config to unprotect the form on the live site. We should reset config after API keys are reset (and/or keep setting off when rolling new version if this can't be handled until migration is complete). But for now, as we are pushing people to use and provide feedback on KB over next couple of weeks, don't want them to be frustrated when they try to reset their passwords.

**Comment by steinmb** [comment]
Addressed in issue #318
