### ISSUE TITLE
Broken image on front page

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#363]
<img width="1166" alt="screenshot 2018-04-21 11 07 10" src="https://user-images.githubusercontent.com/5831053/39082508-737f5110-4554-11e8-930b-4ccc61dfcc96.png">

We will need to figure out what to do with front page (the ELMCIP project stuff should probably just be archived into a separate page and the front redirect to the KB).

But in the meantime, not good to have a broken image on the front page.

**Comment by steinmb** [comment]
commit 2b58dc83df36bab155ba2722ba168237ae680ecd (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Apr 23 21:30:55 2018 +0200

    Issue 363 Image to front page custom block moved

    Prob. side effect coming from issue 322
