### ISSUE TITLE
Tag display on Event record is vertical, not in a horizontal line

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#370]
<img width="1082" alt="screenshot 2018-05-01 13 40 20" src="https://user-images.githubusercontent.com/5831053/39471800-783fbd2c-4d45-11e8-8843-8929ef3df765.png">

Tags are displaying differently than they should (should be in a horizontal list and not take up so much room)

**Comment by elmcip** [comment]
This may be particular to this record. Any guess why though?

**Comment by AlvaroSeica** [comment]
This is happening across records in that content type.

**Comment by steinmb** [comment]
commit 4eaa54d4be99bb8146404153ee8a9137455c3c1a (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Tue Dec 4 01:33:23 2018 +0100

    Issue 370 Event nodes tags not inline

    Change field display settings to allow them to visually
    appare inline.
