### ISSUE TITLE
Book series view problem on Publisher records

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#371]
<img width="1042" alt="screenshot 2018-05-01 20 08 41" src="https://user-images.githubusercontent.com/5831053/39486242-bd7fb910-4d7b-11e8-91c1-00a3a3c7408a.png">
Under Publisher, the series published attached view is incorrectly configured to the wrong field, and is repeating books published rather than actual series published. This should be a priority fix.

**Comment by AlvaroSeica** [comment]
@steinmb @elmcip just noticed the same issue on node/12014.

<img width="1396" alt="bookthug___elmcip" src="https://user-images.githubusercontent.com/6121438/48417381-e891bd80-e752-11e8-982b-3dacac36c6a6.png">

**Comment by steinmb** [comment]
Not 100% sure but I think this is right. Comparing https://elmcip.net/publisher/electronic-book-review-ebr against my local dev. after change.

![screenshot 2018-12-04 at 02 37 41](https://user-images.githubusercontent.com/683617/49412924-7408d800-f76e-11e8-9533-c52625025b04.png)


commit aa36da89d86c94ed742cd2bcc866fb1cd2966c10 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Tue Dec 4 02:41:14 2018 +0100

    Issue 371 Publisher show wrong series records

    View lists wrong nodes.

**Comment by steinmb** [comment]
No feedback. Closing

**Comment by AlvaroSeica** [comment]
That's right, it is good now! On the other hand, there is a view problem when there are double addresses of a publisher--addressed in #416
