### ISSUE TITLE
Maximum results from autocomplete hard coded to 10

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#372]
Fix on this one needed ASAP!

It seems that the autocomplete on nodes searches for the words typed, but only shows 10 results to select from. This becomes a major problem, particularly for my book "Electronic Literature" which as of now it seems cannot be referenced:

<img width="1032" alt="screenshot 2018-05-01 20 43 12" src="https://user-images.githubusercontent.com/5831053/39487864-cca045cc-4d80-11e8-9d5b-435618c3164e.png">

I have a research assistant coming in to work on documenting the book in ELMCIP and working on a companion website like, next week, so I'd really like to see this one get a hot fix.

I'll check later to see if this is just a token thing or caching issue or something, but it looks to me that the problem is as I've described it above. If so, once there are more than 10 records with the same words in them, new records with those words are not possible to cross-ref.

**Comment by steinmb** [comment]
Not a bug but "as designed". The amount of results are limited for performance and for UI reasons. The entity reference widget should have a setting that allow users to override the limit on a field to field basis and there is a issue for is in the works. The Drupal core autocomplete javascript does not have a scroll bar allowing us to list more results without the form blowing out of vertical screen space.

### Issues trying to tackle it.

* https://www.drupal.org/project/drupal/issues/2863188
* https://www.drupal.org/project/entityreference/issues/1700112
* https://www.drupal.org/project/drupal/issues/913418

## Work around 

Until entityreference commit the reviewed improvements from issues above, do we still have to work around it. This is us hooking in and hijacking entity reference and taking full control. By doing so we are duplicating quite a lot of code just to override the maximum results to return to the form.

commit 14e74977c00283e96e7f4a53dd3e5bb5b582393f (HEAD -> issue_372, origin/issue_372)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Oct 3 12:45:05 2018 +0200

    Issue 372 Autocomplete widget items hardcoded to 10

    Take over control of entityreference autocomplete widget until
    a official fix is released.

**Comment by steinmb** [comment]
Tested and pushed to master branch. Part of next release.

commit b426e92ff48198701a7cf49aaf22de682c144d80
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Oct 3 12:45:05 2018 +0200

    Issue 372 Autocomplete widget items hardcoded to 10
    
    Take over control of entityreference autocomplete widget until
    a official fix is released.
