### ISSUE TITLE
Add DOI field to Creative Works and to Critical Writing

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#373]
Digital Object Identifier field should be added.

**Comment by steinmb** [comment]
Dust settled after of NIRD system downtime. Time to return til more productive work than putting out fires.

This as mention above reverts all work in the original branch. Change from link field to text field that req. a real DOI value. When form validate do we use a custom field formatter to render DOI number to a hyperlink that resolve at doi.org.

commit 970cd093081aea87e97850b6f54ddc5bb8f9ff6f (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Nov 29 13:52:53 2018 +0100

    Issue 373 Field validator and field formatter

    Validate that DOI contain a valid value and do not
    start with protocols like https.

commit 7e4239c8166a7cbe968c6e8b85d436177e875493
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Nov 29 13:08:43 2018 +0100

    Issue 373 New field field_doi to store DOI data

    Creative works and critical writing
