### ISSUE TITLE
Add ORCID ID field to Author records

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#374]
ORCID unique identifier fields should be added to author records (linked to ORCID record)

@hannahackermans wrote

>ORCiD is a database of researchers that gives out a unique ID number for every researcher. https://orcid.org/about
>A lot of information in the people records goes out of date when people change affiliations, so there university profiles disappear etc. But with a ORCiD ID you can still find information on the researcher independent from the affiliations.
>Can we add a field to fill in the ORCiD ID of researchers to link them to their ORCiD page?
I.E. Scott's ORCiD ID is https://orcid.org/0000-0002-7401-5075

**Comment by steinmb** [comment]
@hannahackermans I added your info to the issue summary.

**Comment by steinmb** [comment]
![screenshot 2018-11-06 at 11 04 41](https://user-images.githubusercontent.com/683617/48057263-e01a0f80-e1b3-11e8-8f24-c9fb0520c906.png)


commit 03c89ada5171c477f40e54983057be00a784e581 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Tue Nov 6 09:55:49 2018 +0100

    Issue 374 New field to store ORCID link in persons

    Simple link field.

**Comment by AlvaroSeica** [comment]
We need to look into the ORCiD field again. Either we update the descrption txt to highlight that the full URL needs to be inserted, or we allow for insertion of the ID-only code with target https://orcid.org/ + code.

I have noticed that if only the ID is inserted, the target is generated as https://elmcip.net/ + code (ERROR)

See image below (https://elmcip.net/node/10200/edit)

<img width="655" alt="Captura de ecrã 2021-05-27, às 15 31 54" src="https://user-images.githubusercontent.com/6121438/119835079-cb7ffd00-bf00-11eb-8f64-82f6afa622be.png">

<img width="387" alt="Captura de ecrã 2021-05-27, às 15 32 14" src="https://user-images.githubusercontent.com/6121438/119835099-d0dd4780-bf00-11eb-9a59-c3f726ee80b4.png">

**Comment by steinmb** [comment]
@AlvaroSeica moved you comment into a new issue #467 - to avoid re-opening old issues.
