### ISSUE TITLE
Remove NID from display on Platform page

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#375]
<img width="1025" alt="screenshot 2018-05-02 00 39 33" src="https://user-images.githubusercontent.com/5831053/39497010-6d6c7e56-4da1-11e8-820d-41cd7420b3e8.png">

**Comment by steinmb** [comment]
commit 98348ae2df520cca14b47b7f88b1400c8edc70e8 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon May 28 13:33:19 2018 +0100

    Issue 375 Improve platform/software view:platform

    - Removed Nid field from page view /platform. Not needed there.
    Is only part of exported data.
    - Changed view alias (path) /data/platform to /platform
    - Permission: User allowed to view content is granted access to page
    - Permission: All auth users are allowed to export data.
    - Pager ID change to 0 - This change pager URL from /platform?page=0%2C0%2C1 to
    the more understandable /platform?page=1
    - Page performance: Reduced number of items pr. page from 50 to 20.
