### ISSUE TITLE
Uploads issue

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#378]
Re: PT note on uploads -- putting this here for testing and tracking.
--
Hi Stein&Scott,

while working on the Siegen-ADEL database, I discovered a dissertation, created a record and wanted to upload the it as an attachment, but I get this error message.
--

only 4MB, one at a time :-)

2018-08-07 15:55 GMT+02:00 Stein Magne Bjørklund <steinmb@gmail.com>:
Hei Patricia
Thank for reporting. I have reported this issue to the NIRD infrastructure. By the look of it is it due to limited resources in the webserver config.

BTW: What is the size of the PDF file? And do you try to upload one or multiple files in the same post?

> On 7 Aug 2018, at 13:39, Patricia Tomaszek <ptomaszek.usb@googlemail.com> wrote:
> 
> Hi Stein&Scott,
> 
> while working on the Siegen-ADEL database, I discovered a dissertation, created a record and wanted to upload the it as an attachment, but I get this error message:
> 
> <image.png>
> 
> Can anyone make a note and check&fix it?
> 
> Here's the record (Scott will like it, though he would rather like mine to be finished....coming soon though no one knows: when): 
> 
> From Dada to Digital: Experimental Poetry in the Media Age
> https://elmcip.net/critical-writing/dada-digital-experimental-poetry-media-age
> 
> Cheers!

**Comment by steinmb** [comment]
Due to limited resources in the webserver config and not ELMCIP. They fixed it. Patricia confirmed that it was fixed August 8.

### Patricia Wrote

>Hi,
>
>just checked it and it worked out: I was able to upload Beals dissertation, see here:
https://elmcip.net/critical-writing/dada-digital-experimental-poetry-media-age
