### ISSUE TITLE
Sort works by year chronologically on the author's Page

### ISSUE THREAD

**Issue by AlvaroSeica** [elmcip/elmcip#379]
<img width="1102" alt="ottar_ormstad___elmcip" src="https://user-images.githubusercontent.com/6121438/44050389-cccd721a-9f04-11e8-91c3-3784f10656d9.png">

**Comment by steinmb** [comment]
commit b232101dbbf8d0ce41957c45431014ca188a61bb (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Oct 4 12:44:15 2018 +0200

    Issue 379 Views on person page list content sorted by year

    Sort - newest on top
    One display was missing a mini pager. Set to default 20 items.


![screen shot 2018-10-04 at 12 41 30](https://user-images.githubusercontent.com/683617/46469304-4be31400-c7d3-11e8-96c2-50babd59dde8.png)
