### ISSUE TITLE
Do not display gender field

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#381]
After discussion with the ELO community about the complications involved in gathering and publicly displaying gender information, I think we should continue to gather author gender information but not display that information on the author page. This way gender information can continue to be available for faceted search (for example to find all French women author pages) or data exports for research, but we will not produce significant issues by publicly displaying inaccurate information about people's gender.

This should be a relatively simple fix. Let's implement it in the next release.

**Comment by elmcip** [comment]
Scott Rettberg
Admin · 13 hrs · tagAdd Topics
Looking for advice: We have a gender field on biographical records for the ELMCIP Electronic Literature Knowledge Base. We added this I think 5 or 6 years ago because some researchers concerned with gender representation in the field wanted to be able to look at patterns of publication, how differently gendered artists and scholars were represented in the conferences, events, exhibitions, etc. over time -- which seems like a completely sensible use. There are three categories...
See More
29 Comments
2Alan Sondheim and 1 other
Like
Show more reactions
Comment
Share
Comments
Alan Sondheim
Alan Sondheim I'd eliminate it because it seems unnecessary and is going to constantly create complications. If you keep it, you might have a gender optional category - people placing themselves (or not); otherwise, leaving it empty?
Manage
Like · Reply · 12h
Caitlin Fisher
Caitlin Fisher I like Alan’s suggestion of gender optional - and also gender unknown, so people are not misassigned - but gender remains an important category, given the world in which we live. Certainly as useful as nationality. My vote is to keep it.
2
Manage
Like · Reply · 11h
Allison Parrish
Allison Parrish I agree that gender remains an important category. And it does seem like Scott is implying that a "shortcut" for solving the problem of inaccurate gender listings is to eliminate the gender field altogether, which is acceptable given that the gender fi…See More
Manage
Like · Reply · 11h · Edited
Scott Rettberg
Write a reply...

Gökhan Turhan
Gökhan Turhan Keep it and remind the artists to submit any further change to you directly.
2
Manage
Like · Reply · 11h
Allison Parrish
Allison Parrish Speaking from experience, it is *absolutely exhausting* to have to hunt down listings like these and then figure out how to make changes to them (I have updated my information in dozens and dozens of places, many of which required weeks and weeks of wa…See More
1
Manage
Like · Reply · 11h
Scott Rettberg
Scott RettbergYou and 3 others manage the membership, moderators, settings, and posts for Electronic Literature Organization. Requiring consent to list someone’s name would essentially break the database. We record public publication data. I think more people would be upset if we did not list their names as authors or co-authors of work if we abandoned the practice.
Manage
Like · Reply · 11h
Scott Rettberg
Scott RettbergYou and 3 others manage the membership, moderators, settings, and posts for Electronic Literature Organization. And I actually object to the idea that it’s *our* work. Unless you define *our* work as that of the community.
Manage
Like · Reply · 11h
Scott Rettberg
Scott RettbergYou and 3 others manage the membership, moderators, settings, and posts for Electronic Literature Organization. We have never denied anyone’s request to remove their records but we could not have built a record of the field if we asked every author for permission to list them as an author of a work they authored. We simply don’t have the resources and the database would not exist in this case.
Manage
Like · Reply · 11h
Scott Rettberg
Scott RettbergYou and 3 others manage the membership, moderators, settings, and posts for Electronic Literature Organization. But I’m inclined to agree that gender might not fall into the scope of what we can reasonably document.
1
Manage
Like · Reply · 11h
Allison Parrish
Allison Parrish I'm saying that it's certainly not the work of the person listed, and especially an unfriendly burden on an individual updating a gender marker, for the reasons I outlined. That person did not create the listing; they may not even care to be listed in the database in the first place; it can't be their responsibility to maintain the listing.
1
Manage
Like · Reply · 11h
Scott Rettberg
Scott RettbergYou and 3 others manage the membership, moderators, settings, and posts for Electronic Literature Organization. Ultimately this database is based on a community caring about it and caring for it. I'm not saying that every author should be deeply invested in that care. But the assumption that it is a service that simply exists is very contingent.
Manage
Like · Reply · 10h
Allison Parrish
Allison Parrish If it's intended to be a database of public publication information, then another solution might be to remove the abstraction of "Author" entirely, or at least the landing page for individual authors who don't give positive consent (again, retaining th…See More
1
Manage
Like · Reply · 10h
Allison Parrish
Allison Parrish The community care and community building aspect of the database is very important. But I want to suggest that a community—no matter how well intentioned—is not always the best entity for making decisions about how to talk about an individual's gender. (And this is especially the case for individuals on the margins of the community.)
Manage
Like · Reply · 10h
Scott Rettberg

Write a reply...


Alma Pérez
Alma Pérez I agree to keep it. this is an important category if we want to be aware and be sensitive to gender disparities. Right now the database shows 1713 identified male over 891 identified as female, which is very unbalanced. Reminding this category as optio…See More
Manage
Like · Reply · 11h
Alma Pérez
Alma Pérez An alternative would be to ask for "prefered pronoun"....
Manage
Like · Reply · 11h
Lori Emerson
Lori Emerson I think gender is a useful category but also very complicated and requires complicated and sensitive handling in a way that I'm guessing you don't have resources for...would be neat if it's possible to do something like what Allison Parrish suggests - …See More
1
Manage
Like · Reply · 10h
Scott Rettberg
Scott RettbergYou and 3 others manage the membership, moderators, settings, and posts for Electronic Literature Organization. I think this would be possible.
Manage
Like · Reply · 10h
Lori Emerson
Lori Emerson it's a wonderful community/community-building resource! I can also imagine inaccurate gender info making some people feel like they're not included in the community...
1
Manage
Like · Reply · 10h
Scott Rettberg
Scott RettbergYou and 3 others manage the membership, moderators, settings, and posts for Electronic Literature Organization. Though I'm not sure we should maintain gender data at all. If we hide the data we increase the likelihood of inaccuracy.
2
Manage
Like · Reply · 10h
Lori Emerson
Lori Emerson that's true - I haven't looked recently but I bet there are all kinds of identity categories that you weren't/aren't able to include
Manage
Like · Reply · 10h
Scott Rettberg
Scott RettbergYou and 3 others manage the membership, moderators, settings, and posts for Electronic Literature Organization. I think it's important to emphasize that we only began collecting this information because it was requested by authors and researchers specifically interested in keeping track things like gender representation the field over time. From a "meta" standpo…See More
2
Manage
Like · Reply · 10h · Edited
Scott Rettberg
Scott RettbergYou and 3 others manage the membership, moderators, settings, and posts for Electronic Literature Organization. I'll talk it through with our editorial team and welcome more input, but maybe the best thing to do is to publish some data on the (collective) gender info we have now and then eliminate the field.
2
Manage
Like · Reply · 10h · Edited
Jason Nelson
Jason Nelson I have an idea. Keep the database the way it is. Although I would allow another field to open if the artist chooses other. HOWEVER, also have a response form for very specific fields, such as gender, that allows people to send the ELMCIP team a message about changing an entry. Limit that form to very specific meta-data fields, so as not to have people using it as an editing tool.
Manage
Like · Reply · 6h
Jason Nelson
Jason Nelson Alternatively..... you could have the gender field hidden. Keep it there...but hidden. AND, if an artist wants to have that field revealed and open, they can create an account, fill out the proper entry for that field and then check a box to let it be visible.
Manage
Like · Reply · 6h
Jason Nelson
Jason Nelson So you are basically keeping the field for data collection. But also recognizing that some personal data will change and is highly personal. So an artist can log-in and make that data field visible to the world or they can keep it hidden. But it would …See More
Manage
Like · Reply · 6h
Jason Nelson
Jason Nelson And thus the act of making it visible by the artist/author would ensure the field is accurate. And if, as in the case you noted, it is not accurate, the field would not be visible to the world.
Manage
Like · Reply · 6h
Alan Sondheim
Alan Sondheim This is also perhaps too complicated, and many artists might either not know about it or ignore it. There's no good answer, no way to please everyone; the best thing to do is to make it simple, supple, and perhaps eliminate it if it continues to be problematic.
Manage
Like · Reply · 5h
Scott Rettberg
Scott RettbergYou and 3 others manage the membership, moderators, settings, and posts for Electronic Literature Organization. We could leave the field in place but not display the data, as suggested earlier. As I think through the mechanics, that's relatively simple -- and flushing data altogether out of the system can create new problems. We will also put into place a cleare…See More
Manage
Like · Reply · 12m · Edited
Scott Rettberg
Scott RettbergYou and 3 others manage the membership, moderators, settings, and posts for Electronic Literature Organization. I think we could ultimately create a facility to for authors to "claim and approve" their record. Any author can, of course, already simply request an account and edit their record. But maybe we could mark records in that way.

**Comment by steinmb** [comment]
commit 7a20b555b39e7af86223b0c5fc64d9ee674fa4cf (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Oct 4 11:47:42 2018 +0200

    Issue 381 Do not render gender field on person nodes
    
    Complications involved in gathering and publicly displaying
    gender information.
