### ISSUE TITLE
Change help text for Gender field

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#382]
Along with issue #381 -- the help text on the entry field for Gender should indicate that the information  will not be publicly displayed on the author page.

**Comment by elmcip** [comment]
"Indicate the author's gender. Note: this information will not be publicly displayed on the author page but may be used in faceted search for quantitative research."

**Comment by steinmb** [comment]
commit f01a4aea1ac00c461d4f483e64bfc2f8e5ebe49b (HEAD -> master)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Oct 4 12:00:19 2018 +0200

    Issue 382 Improve gender field help text

    Change it to reflect issue 381. We no longer render this field on
    the person node.
