### ISSUE TITLE
What happened to the "Description in other language" field?

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#385]
We seem to be missing a field on Creative Works. We had a "Description in other language" (or similar name) field, where authors could for example provide a description of a work that was written in Spanish in Spanish (along with the English description). It seems to not be there anymore on the entry form. Where did it go?

**Comment by steinmb** [comment]
Are you thinking about `Description (in original language)` ?

**Comment by elmcip** [comment]
Yes.

**Comment by steinmb** [comment]
It is still there. You first select the language of the description, then it show up.
