### ISSUE TITLE
Add "Records edited" to user dashboard

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#386]
One of the DIKULT 207 students today noticed that on their dashboard / landing page, records they created appear, but not records that they have edited. It would be useful to have a record not only of new records created, but also works that a given user has modified (for example, my students are now trying to complete and approve stub records. There is no way for them to see what they have recently done or to pick up where they left off.

**Comment by elmcip** [comment]
Students are wondering why we still don't have this functionality. Let's look into adding to the next release?

**Comment by steinmb** [comment]
Going to have a look at this. Thank you for pinging the issue.

**Comment by steinmb** [comment]
Related to issue #405 @hannahackermans nicely provided a detailed report.

**Comment by steinmb** [comment]
Cleaned up and added new pane. Currently testing the change. Here is what we so far have:

commit b0c92b67d1e401cbf0ce14a83ac0e44ed4706dc9 (HEAD -> issue_386, origin/issue_386)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Sep 5 23:29:06 2019 +0200

    Issue 386 Add "Records edited" to user profile

    Allow users to quickly find last edited nodes

# Before

![Screenshot_2019-09-05 ELMCIP Electronic Literature as a Model of Creativity and Innovation in Practice](https://user-images.githubusercontent.com/683617/64382976-f5f79b80-d035-11e9-88f3-e4cbe737a6fd.png)

# After

![Screenshot_2019-09-05 ELMCIP Electronic Literature as a Model of Creativity and Innovation in Practice(1)](https://user-images.githubusercontent.com/683617/64382974-f5f79b80-d035-11e9-933f-d58ce802cc3f.png)

**Comment by steinmb** [comment]
Looks OK. Cherry picked into master and part of this release. 
commit e0078efdb67e6699f50b18306b7747097dc65461 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Sep 5 23:29:06 2019 +0200

    Issue 386 Add "Records edited" to user profile

    Allow users to quickly find last edited nodes

**Comment by elmcip** [comment]
This works. There's still a lot of cleanup to do on the user dashboard, but the records edited are now indicated.
