### ISSUE TITLE
Change Language of original description help text

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#387]
Note: this is confusing now -- I understand why we wanted to tie the field to the language and only have it appear if a language is selected, but now we need to clarify how this works for the contributor.

I think we change the title of the field to "Description in original language"

Help text something like "If the work was produced in another language (for example French, German, etc.) add a description in the original language by first selecting the language and then adding the description in that language in the field that appears."

## Content types

* [x] Creative Work
* [x] Critical Writing
* [x] Teaching Resource
* [x] Event

## How to test

Check all it work as expected in all content type the field is in use.

**Comment by steinmb** [comment]
For the record - The change was done in https://github.com/elmcip/elmcip/issues/177

Good suggestion about help text update but there is two help text in here. I think the other also should be updated. Perhaps remove that part om leaving it empty?

> If the work is not written in English, write a brief abstract in the original language. If you source the abstract from elsewhere, indicate the source in parentheses after the abstract. Leave this field empty if the original language of the work is English.


## Form before selecting description language

![screen shot 2018-08-29 at 17 28 11](https://user-images.githubusercontent.com/683617/44801616-6f51e800-abb1-11e8-9b02-ba2654ca671a.png)


## Form after choosing lang. Here German

![screen shot 2018-08-29 at 17 30 58](https://user-images.githubusercontent.com/683617/44801617-6f51e800-abb1-11e8-937d-cf18bd253a9b.png)

**Comment by elmcip** [comment]
Yes, remove the second help text. Address it all in the first.
-----------
Scott Rettberg
Professor of Digital Culture, University of Bergen
Consulting Professor, Digital Arts and Humanities, National University of Ireland, Galway

http://crchange.net <http://crchange.net/> CRchange projects
http://elmcip.net/knowledgebase <http://elmcip.net/knowledgebase> ELMCIP Electronic Literature Knowledge Base
http://retts.net <http://retts.net/>

**Comment by steinmb** [comment]
commit e468812f8624d56becfaef924c2777f07cce12eb (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Oct 4 13:06:54 2018 +0200

    Issue 387 original description help text improvements

    Affect content types:
     Creative work
     Critical writing
     Teaching resource
     Event


# After change

![screen shot 2018-10-04 at 13 04 06](https://user-images.githubusercontent.com/683617/46470333-8601e500-c7d6-11e8-9966-6ab0958a37ea.png)
