### ISSUE TITLE
Display Critical Writing Referencing this Platform on Platform page

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#388]
As far as I can tell, when a work of critical writing has a reference to a particular platform, the cross-reference to the platform does not display on the record for the platform, as it should

**Comment by steinmb** [comment]
Yes. It was never implemented when platform/software got created.

commit f85b425d5fbab72de7b9ba29491890744621bdde (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Feb 3 11:53:41 2020 +0100

    Issue 388 Platform/software show critical writing ref

**Comment by MagnusKnustad** [comment]
I see on the platform-pages that there is a box with the heading "Works Developed in this Platform:" and a list of works in a table with columns called "Work title", "Author", "Language" and "Year".
Is that what was missing? If so, it's not missing anymore...

**Comment by MagnusKnustad** [comment]
I checked again, and I found several different examples of platform being referenced in critical writings. I think this one can be closed.
