### ISSUE TITLE
Individual records of databases and Archives displaying multiple times on front page

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#389]
Not sure if this was just a mistake someone made by hand. But look here: 

![screenshot 2018-09-05 15 29 06](https://user-images.githubusercontent.com/5831053/45096549-1211e580-b121-11e8-95e0-fa18bf7e28cb.png)

the record for the Rutgers-Camden Archive is save three times as three separate records. Something funny happened there.

**Comment by steinmb** [comment]
Unable to re-produce. They are different records. Look like the user created the same one three times. The minutes between each creation also suggest that is the case.
