### ISSUE TITLE
Cannot add screenshots to databases and archives record

### ISSUE THREAD

**Issue by hannahackermans** [elmcip/elmcip#390]
I am creating a "Databases and Archives" entry and I wanted to add some screenshots but as you can see below you get the familiar "you have not selected anything" error (also discussed in #332 )
I have had this error a lot when in fact after clicking it away, it would have added the media anyway despite the error. In this case nothing appears so I cannot add screenshots to the record. 
This is something that just happened while I was working in the KB. Let me know what types of wider tests (on different file types, different record types?) you need to fix it.
<img width="783" alt="screenshot 2018-09-24 13 31 20 1" src="https://user-images.githubusercontent.com/18713442/45950211-200ba580-bfff-11e8-8359-388bcf6c2c95.png">

**Comment by steinmb** [comment]
Some kind of javascript problem with the media library browser. What is your OS, web browser and web browser version?

**Comment by hannahackermans** [comment]
> What is your OS, web browser and web browser version?
Windows, Firefox 62.0

**Comment by hannahackermans** [comment]
> What is your OS, web browser and web browser version?

windows, firefox 62.0

**Comment by steinmb** [comment]
Thank you.

**Comment by steinmb** [comment]
I just noticed in your screen shot. The `OK` button. The one you have should not be there. Not sure where it is coming from. We have to look into that. The media browser introduce two buttons. `Previous` and `Save`. Pressing the OK would cause a unexpected result.

![screen shot 2018-10-04 at 13 52 21](https://user-images.githubusercontent.com/683617/46472285-01669500-c7dd-11e8-8191-e71f59a85f9d.png)

Though still confusing why tour screen shot do not have `Save` –button.

**Comment by steinmb** [comment]
Very hard to track down though the fix is simple. Tested locally as user in belonging to your user groups.

commit cb3c999077dcc0bedd958bedd491406e082506d8
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Tue Nov 6 02:43:18 2018 +0100

    Issue 390 Fix name space collision with the Media module

    media.css prove to cause problem with jquery
