### ISSUE TITLE
Events referenced in database record not hyperlinked

### ISSUE THREAD

**Issue by hannahackermans** [elmcip/elmcip#392]
In the databases and archives record it is possible to fill in which events the database has ben presented at. This is done via cross-referencing to the nodes of these events. 
<img width="715" alt="screenshot 2018-09-25 16 01 31" src="https://user-images.githubusercontent.com/18713442/46019935-751de900-c0dd-11e8-9342-aee140a0f486.png">

In View the information is listed as regular text, not as a hyperlink. Considering we enter the information cross-referenced to the event records, I think the view should reflect this as well.
<img width="725" alt="screenshot 2018-09-25 16 01 38" src="https://user-images.githubusercontent.com/18713442/46019990-97b00200-c0dd-11e8-9ce5-c10636246faf.png">

screenshots taken from ELMCIP database page: https://elmcip.net/node/3946

**Comment by steinmb** [comment]
Good catch.

**Comment by steinmb** [comment]
commit d30f5cb2c07ac75efaea406a6b4ff0b8b25ab48b (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Oct 4 11:52:12 2018 +0200

    Issue 392 Events referenced in database record not hyperlinked
    
    These should be links.
