### ISSUE TITLE
Enable the Librarian user group a way to flag/revoke "approved by librarian" records

### ISSUE THREAD

**Issue by hannahackermans** [elmcip/elmcip#394]
Hi Stein, as you may know, we are starting to work together with the University library.
Our librarian Adriana is going to go through records to check metadata. I have done some tutorials with her and based on that I have a number of issues that I will create here. We will meet up again with more issues and advice later.

Can you create a new account role called "Librarian" which will, for the moment, only be Adriana? 
The only privilege that would set it apart from an editor role would be to add the option of "librarian approved" or "metadata approved" to the options for record status. This way, Adriana can indicate which records she has checked and approved.

## Permissions

* Toggle on/off Approved / Not approved should be possible by the librarian.
* Result of the flag should only be visible to groups: librarian, administrative editor and adminisitrator.

**Comment by elmcip** [comment]
New role should be the same as editor, but with ability to change status of new "Library approved" field.

New field: Toggle on/off Approved / Not approved. Field should be visible only to librarian, administrative editor, adminisitrator.

**Comment by steinmb** [comment]
Did these while waiting for feedback. Also went ahead and cherry picked them to master.

f983f7b (HEAD -> master, origin/master, origin/HEAD) Issue 394 New module - Flag
a8b6514 Issue 394 Use hook_ds_pre_render_alter instead of node preprocess
99cd40f Issue 394 Update permissions settings
262b68d Issue 394 Flag custom code refactoring
9043908 Issue 394 Track user role permissions
074cbcc Issue 394 Flag Librarian permission settings
5e1d951 Issue 394 Enable flag sudo field on work and creative writing
5e0b871 Issue 394 Export Librarian flag settings
066ea62 Issue 394 Only allow Library group use of Flags

**Comment by elmcip** [comment]
Critical Writing and Creative Work
-----------
Scott Rettberg
Professor of Digital Culture, University of Bergen

My new book Electronic Literature is now available from Polity: http://politybooks.com/bookdetail/?isbn=9781509516773

**Comment by steinmb** [comment]
@hannahackermans These changes is part of https://github.com/elmcip/elmcip/milestone/14 and you should test it out in production. issue #398 is prob. part of a fully working work flow for the librarian.

**Comment by hannahackermans** [comment]
(let me know if this needs to be a separate issue)

Thank you for making the Librarian approved status. 
I do have 2 requests about it:
1) Simply question: Can you make it so that I can give people a librarian role when adding people? Librarian is not currently one of the options for me, which means I also cannot test how it is working with a test account.
2) Difficult question: Currently every single record says "Not approved by librarian" simply because Adriana has not approved the records yet. The text suggests that the librarian actively disapproved the record. Would is be possible to differentiate 3 options:
- if the record has not been reviewed by the librarian there is no text (or "not yet reviewed by librarian")
- if the record is reviewed and disapproved, the text "Not approved by librarian" 
- if the record is reviewed and approved, the text "approved by librarian"
I realize this is a difficult question because the first two both has 'off' on the toggle, but I think we need  to find a solution for this. As a temporary band-aid, it might be better if we only show the text "approved by librarian", and no text in the other two. But eventually, we need to differentiate the three because we would want to improve records that are disapproved by librarian.

**Comment by elmcip** [comment]
We either need to have the librarian working on this, or turn it off.

**Comment by steinmb** [comment]
Adding untested

![Screen Shot 2020-01-30 at 16 32 33](https://user-images.githubusercontent.com/683617/73464035-8edcd980-437e-11ea-80ab-fee827a5174f.png)

commit ba52c3632be373ae3d788dd493b5f771f27c7dfa (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Jan 30 16:33:48 2020 +0100

    Issue 394 Critical writing page filter by record status

**Comment by elmcip** [comment]
Ok this works.

**Comment by steinmb** [comment]
Issue #453 is replacing this feature and issue. Closing.
