### ISSUE TITLE
Give librarians a list of records approval status

### ISSUE THREAD

**Issue by hannahackermans** [elmcip/elmcip#398]
This is the list of records that are not yet reviewed yet: https://elmcip.net/category/record-status/not-yet-reviewed
The columns are only title and author. 

It would make it a lot easier for Adriana if we could add a column with the content type. That way, she can easily start be just checking on the critical writing records. 
<img width="960" alt="screenshot 2018-10-03 16 53 14" src="https://user-images.githubusercontent.com/18713442/46418841-da508a80-c72c-11e8-9cf6-059cc88f5614.png">

**Comment by steinmb** [comment]
I would think she should use - https://elmcip.net/knowledgebase/status that already do this. Sure we can add a content type filter on https://elmcip.net/category/record-status/not-yet-reviewed but be aware that this would apply to all taxonomy terms you navigate by. example - `category/tags/science-fiction` and so on.

Also since in #394 did we add another tag/flag they should use that they approve that is different from the more crowd sourced record status most users have access to, perhaps none of these is what they need to keep track?

**Comment by hannahackermans** [comment]
Thank you, I did not know about this page, I will send the link to our librarian.

**Comment by steinmb** [comment]
As I wrote above. That page do not expose the new approved system so I think it is pretty useless for them. What we need is something like this:

<img width="651" alt="screenshot 2018-12-06 at 15 18 04" src="https://user-images.githubusercontent.com/683617/49589793-96674500-f96a-11e8-885f-e172490ad057.png">
<img width="651" alt="screenshot 2018-12-06 at 15 18 53" src="https://user-images.githubusercontent.com/683617/49589794-96674500-f96a-11e8-8085-ac7d64f544ec.png">

**Comment by steinmb** [comment]
Tagging for review of the screenshots in the issue but grab the example views before moving on while waiting for feedback:

commit 27de3052c5cde632518f368307537280528753af (HEAD -> issue_398, origin/issue_398)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Dec 6 15:43:14 2018 +0100

    Issue 398 Allow us to view and filter content approved by library

    URL: /knowledgebase/library_status

**Comment by elmcip** [comment]
So this is as they wanted it, but we also wanted the filter on critical writing page. Looks like you have added that to test? If so, @hannahackermans can you see if issue is ready to close? Note: we will also want this filter on "See all" pages for all other content types. Should I create a separate issue?
<img width="1085" alt="Screenshot 2020-01-31 13 55 10" src="https://user-images.githubusercontent.com/5831053/73540932-74b00380-4431-11ea-998c-64385d48fd3c.png">

**Comment by steinmb** [comment]
Spin out a new one.
