### ISSUE TITLE
add ORCiD to people record

### ISSUE THREAD

**Issue by hannahackermans** [elmcip/elmcip#399]
ORCiD is a database of researchers that gives out a unique ID number for every researcher. https://orcid.org/about

A lot of information in the people records goes out of date when people change affiliations, so there university profiles disappear etc. But with a ORCiD ID you can still find information on the researcher independent from the affiliations. 

Can we add a field to fill in the ORCiD ID of researchers to link them to their ORCiD page?
I.E. Scott's ORCiD ID is  https://orcid.org/0000-0002-7401-5075

**Comment by elmcip** [comment]
see issue #374

**Comment by hannahackermans** [comment]
Glad to know this is already in the pipeline!

**Comment by steinmb** [comment]
Closing as duplicate.
