### ISSUE TITLE
Improve autocomplete widget

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#403]
Follow up of issue #372. We use a lot of autocomplete. We should make sure it work really good.

### Issues trying to tackle it.

* https://www.drupal.org/project/drupal/issues/2863188
* https://www.drupal.org/project/entityreference/issues/1700112
* https://www.drupal.org/project/drupal/issues/913418

## Work around in place

Current fix is https://github.com/elmcip/elmcip/commit/14e74977c00283e96e7f4a53dd3e5bb5b582393f, This is us hooking in and hijacking entity reference and taking full control. By doing so we are duplicating quite a lot of code just to override the maximum results to return to the form. Still generic search terms like 'electronic literature` result in much more than there is room for, more that 60 with the current data set.

## Scope

Allow us to expose lager search result sets. We need to pay attention to widget accessibility hwere.

## Suggested fix

Perhaps leverage js in a custom as a widget,  use jquery-ui to provide a scrollbar for the result coming from the AJAX call. We might need to override drupal core autocomplete.js for this.

**Comment by steinmb** [comment]
It still need work though. This should improve the situation. We consume more memory and time. We have to test this out in production.

commit c305a40d475e0e828cc9149ba2fb04ba9daeb7a9 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Sep 6 21:06:25 2019 +0200

    Issue 403 Sanity check to prevent timeout and run out of memory

commit d19b458a38c15c0ce1905f04b25058174dda3273
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Sep 6 19:59:50 2019 +0200

    Issue 403 CSS to control large result set

    Introduce a vertical scrollbar instead of default expanding list. We might return
    hundreds of search results since we no longer limit number of hits.

commit 9185b295099049024dafd6cc673514b301399ae6
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Sep 6 19:57:27 2019 +0200

    Issue 403 Do not pass in search string just to then overwrite it

commit bef29eff6c50603a671479798ef70f8b4fc8e689
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Sep 6 19:16:09 2019 +0200

    Issue 403 Refactor autocomplete

commit 9007ffa8862ea06cff3c4aa92ed7e579f4871a45
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Sep 6 18:06:19 2019 +0200

    Issue 403 Moving autocomplete into separate file

    - Keep it clean

**Comment by elmcip** [comment]
How should this be reviewed? As far as I can tell, it is limiting the number of autocomplete suggestions to 6. Is that how it should work?

**Comment by steinmb** [comment]
It is not 6, it is 800. You prob. got tricked by the auto-hiding scrollbar in MacOS.

<img width="752" alt="Screenshot 2020-01-31 at 15 09 53" src="https://user-images.githubusercontent.com/683617/73548052-6c12f980-4440-11ea-9236-30d211e11f87.png">

The ting to test is the user experience. We might be experience us bumping into memory problem or performance problem. Here is me testing locally on a very slow computer running php with xdebug enabled, aka, not production setup.

Have a look me searching for a single letter:

[Screen Recording 2020-01-31 at 15.15.16.mp4.zip](https://github.com/elmcip/elmcip/files/4139916/Screen.Recording.2020-01-31.at.15.15.16.mp4.zip)
