### ISSUE TITLE
Search engine should ignore some stop words

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#406]
The search engine should ignore the words "The, a, an, and" to improve results.

## How to test

Search and play around with the search engine

**Comment by steinmb** [comment]
Adding support for stop words https://en.wikipedia.org/wiki/Stop_words and rebuild search index. As a starting point added I:

```
but
did
the this that those
etc
a an
if
on
which
```

Here is a example of stop words in English http://xpo6.com/wp-content/uploads/2015/01/stop-word-list.txt We should perhaps make a our own version of something like this?

We also need to make sure we only run the English stop word match on, well English text fields. As a starting point we do it on the fields:

```
Title
Short description » Text
Abstract (in English) » Text
Description (English) » Text
Description » Text
Description » Text 
```

**Comment by elmcip** [comment]
Difficult to figure out how to tell if this is working, but I think we can trust you on it?

**Comment by steinmb** [comment]
As I wrote above. It is running on only in use on those specific fields. If we still feel we are getting unwanted results we should perhaps have a closer look but also run more tests. 

Perhaps testing for pre-defined sentences/strings would give us some measurable results before/after kind of thing?

**Comment by steinmb** [comment]
This looks OK to me. Closing
