### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by AlvaroSeica** [elmcip/elmcip#407]
@steinmb do you know what is happening in certain pages, such as elmcip.net/person/jason-edward-lewis

<img width="795" alt="503_service_unavailable" src="https://user-images.githubusercontent.com/6121438/47623294-00b7da80-dacd-11e8-8572-67bdcf28a9a2.png">

**Comment by steinmb** [comment]
NIRD outage. AKA, infrastructure thingy out of our control.
