### ISSUE TITLE
Only administrators have permission to use administration toolbar

### ISSUE THREAD

**Issue by hannahackermans** [elmcip/elmcip#410]
I don’t know if this is intended (could not find it in older issues), but my top taskbar in the KB is gone :(

<img width="955" alt="screenshot 2018-12-12 09 08 11" src="https://user-images.githubusercontent.com/18713442/49932060-6e2a9980-fec8-11e8-86a3-3d8b9e976de4.png">

I still have all the permissions and I can use URLs to go to admin/people , but it would be very handy to have the taskbar back.

**Comment by steinmb** [comment]
Only administrators have access to `administration toolbar` and as the name correctly reflects, mostly useful for users doing admin.

* Suggestion: We give users that have access to "Use the administration pages and help" also access to the administration toolbar.

**Comment by steinmb** [comment]
commit fad0923db04efdea6378a953d2c639f93d918d99 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Feb 22 14:32:53 2019 +0100

    Issue 410 Allow administrative editor use of admin toolbar

    - Make sense then these users also do light admin work.
    - Revoke this group access to admin content types
