### ISSUE TITLE
ELMCIP is down

### ISSUE THREAD

**Issue by AlvaroSeica** [elmcip/elmcip#413]
<img width="973" alt="503_service_temporarily_unavailable" src="https://user-images.githubusercontent.com/6121438/52778723-f18e7580-3046-11e9-886d-cfd8e0785634.png">

**Comment by steinmb** [comment]
Down, and still down to problems with Norwegian research infrastructure (NIRD) https://opslog.sigma2.no/ Nothing we can do. https://elmcip.net is now running outside NIRD systems until they have addressed all issues.
