### ISSUE TITLE
Add Publication Type facet to search

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#419]
Add this so that we can drill down on type of critical writing.

## Changed
Content types that have a field for publication type (or similar) are:

- Creative Works (publication type)
- Critical Writing (publication type)
- Teaching Resources (Type of Resource)
- [Publishers and journals, see issue #421]
- Events (Event type)
- Databases and Archives (Project Type)

## How to review

* Go to https://elmcip.net/search/
* Play around with the type facet filter enabled

**Comment by hannahackermans** [comment]
As we discussed last week, we would like to add a “publication type”-filter to the search results. 

Different content types (creative works, critical writings, etc) have different publication types. Scott’s idea is to only use the publication type for critical writing. @steinmb, how difficult would it be for the right publication type-filter to show up after someone selects a content type? 

For example, is it possible to search for something and then select for example creative work and then have a filter appear for the publication types of creative works? 
I realize the idea for this filter came from the problems with finding Scott’s book, but I think that having a publication type filter for creative works or event might be even more useful. 

Content types that have a field for publication type (or similar) are:
Creative Works (publication type)
Critical Writing (publication type)
Teaching Resources (Type of Resource) 
[Publishers and journals, see issue #421]
Events (Event type)
Databases and Archives (Project Type)

sidenote: do we already have an issue for adding filter options to more content types on their list page? (the way we have, for example on critical writing: https://elmcip.net/critical_writing) If not, this might be an editorial board project later on, and this would also improve the searchability of (sets of) works)

**Comment by steinmb** [comment]
Mapping to fields to be added to KB search index and later activated as a facet:

* [ ] Add to KB search index: Creative works - Publication type - field_pubtype_tax
    * [ ] Activated facet block
* [ ] Add to KB search index: Critical works - Publication type - field_pubtype_tax
    * [ ] Activated facet block
* [ ] Add to KB search index: Databases and Archives - Project Type - field_project_type
    * [ ] Activated facet block
* [ ] Add to KB search index: Teaching Resources - Type - taxonomy_vocabulary_4
    * [ ] Activated facet block
* [ ] Add to KB search index: Events - Event type - taxonomy_vocabulary_2
    * [ ] Activated facet block
* [ ] Add to KB search index: Publishers and journals - Issue #421
    * [ ] Activated facet block

**Comment by steinmb** [comment]
Most of the filters are available at https://elmcip.net/search/ Take them from a spin.

**Comment by steinmb** [comment]
Created issue #428 to make sure we do not forget to add Publishers and Journals to the search index.

**Comment by steinmb** [comment]
Issue to me look fixed. Closing
