### ISSUE TITLE
Autocomplete cannot find Electronic Literature

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#420]
Fix it!

Best would be for Autocomplete to sort by shortest matching title first.

**Comment by steinmb** [comment]
Related to issue #403

**Comment by steinmb** [comment]
In issue #372 we doubled the amount results returned by the widget though if you search for the generic term `electronic literature` you get more than that. Upping the amount of result returned in  `elmcip_autocomplete_callback_get_matches` callback to even 60 do not address it.

![Screen Shot 2019-09-05 at 12 32 29](https://user-images.githubusercontent.com/683617/64358694-3a1f7780-d007-11e9-8830-a3cd59b8956f.png)

Going to close this as a duplicate to #403 that I just moved into 1.31 release. Currently testing levering Views returning list of entities to the autocomplete widget.
