### ISSUE TITLE
Tags on events display vertically rather than horizontally

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#427]
Tags on events display as a vertical list rather than as a horizontal list, eating up lots of space and being ugly.
![Screenshot 2019-08-27 15 26 27](https://user-images.githubusercontent.com/5831053/63775359-748a6580-c8df-11e9-8e50-5bc68037f8c0.png)

**Comment by steinmb** [comment]
Thank you for reporting - A duplicate issue of #370
