### ISSUE TITLE
Add Publication Type facet search to Publishers and Journals

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#428]
Follow up of issue #421 and #419. After we roll version 1.31 can we update the search enngine config and re-build the search index.

## Scope

* [x] Add to KB search index: Publishers and journals - Issue #421
    * [x] Activated facet block

## How to test

* Go to https://elmcip.net/search/
* Verify that Publication type filter is working. Note. Do no appear if there is no publications nodes that use this new field. Make sure at least one is updated with a publication type.

**Comment by steinmb** [comment]
@hannahackermans Updated config after I rolled version 1.31 a few days ago and I ready to be tested

**Comment by elmcip** [comment]
Bingo, this works
