### ISSUE TITLE
change help text 'pages' in critical writing

### ISSUE THREAD

**Issue by hannahackermans** [elmcip/elmcip#429]
We have two librarian working on the KB this semester to improve and approve records of monographs with the end goal of adding the data from the KB to the library system.
One thing that is important for the library is the total number of pages of a book. 

We already have a 'pages' field in critical writings, which is used for give the beginning and end page of articles in journals or chapters in books. 
I would like to add a sentence to the field help text to include total pages for whole books:

> If the critical writing is published in a journal or book, enter the start and end page numbers, separated by a hyphen (e.g. 65-77). Use the complete number (e.g. 277-297). If the critical writing is a whole book, enter the total number of pages (e.g. 235)

**Comment by elmcip** [comment]
The help text is good, but we should change the field label from "Page Numbers" to "Pages" as it does not makes sense with the current label if we are also using the field to indicate total number of pages.

**Comment by steinmb** [comment]
commit 665b02308f66842179332f7c88239a2b74204039 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Jan 31 16:53:11 2020 +0100

    Issue 429 Change filed label

![Screen Shot 2020-01-31 at 16 50 42](https://user-images.githubusercontent.com/683617/73553428-3d9a1c00-444a-11ea-8d99-c996b7bcf9b4.png)

![Screen Shot 2020-01-31 at 16 51 02](https://user-images.githubusercontent.com/683617/73553444-425ed000-444a-11ea-9baf-e61fd0027280.png)
