### ISSUE TITLE
Install and use Solr as search engine

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#430]
Follow up from issue #341 where we due to time constrains by keeping the scope as small as possible choosed not to implement Solr though we in issue #36 pave way for this to happen one day.

Ref: https://lucene.apache.org/solr/

## Scope

* [x] Get a Solr 7.x instance that store our search indexe(s) installed on Norstore
* [x] Start testing out new search on a new path, example: https://elmcip.net/test/search
* [x] When we har happy, stop using MariaDB as search backend.
* [x] ~~Write hook_update_N() that uninstall `search_api_db` or loosen the dependencies on `search_api_db` from `elmcip_search`.~~

## How to test

At launch should search return about the same results as today though no facets on the test page.

*  https://elmcip.net/test/search - You need to be logged in to access it.

**Comment by steinmb** [comment]
A test instance have been ordered. All we have to do now is wait.

>From: Thierry Toutain <thierry.toutain@usit.uio.no>
>Subject: Re: ELMCIP Solr instance
>Date: 19 September 2019 at 10:56:36 CEST
>To: Stein Magne Bjorklund <steinmb@smbjorklund.com>
>
>Hei,
>den er skrevet på todo list.
>Vi sier fra når vi har opprette noe dere kan teste,
>   Thierry

**Comment by steinmb** [comment]
They have a non working 7.7.x version in the works. Awaits feedback on my latest finding in the installation.

**Comment by steinmb** [comment]
@elmcip Solr backend up and running.
I will keep it in test for a few weeks to make sure it perform and is stable. https://elmcip.net/test/search a test page for the new index. The Index do not have any facets enbabled and do not contain all fields as our current but should perhaps be enough for a rough test.

![Screen Shot 2020-01-27 at 13 33 41](https://user-images.githubusercontent.com/683617/73175097-b2e3b500-4109-11ea-819c-b5ebb9144b71.png)

**Comment by elmcip** [comment]
Works as a rough test, though we want the facets and the same preview as we currently have. But the relevance actually seems better.

**Comment by steinmb** [comment]
Solr have been stable. Going to swap out the search backend storage in productions. Remove needs review tag.

**Comment by steinmb** [comment]
1. Swaped out MariaDB as search backend.
1. Removed test search page
1. Removed MariaDB search backend config, make sure we drop all old indexed data
1. Reindexed with Solr
1. Going to keep search_api_db in the application stack. Useful for local testing if people do not have a Solr instance available.
