### ISSUE TITLE
Really irritating typo on User Dashboard

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#432]
<img width="380" alt="Screenshot 2019-09-26 15 08 51" src="https://user-images.githubusercontent.com/5831053/65690637-c99cd100-e06f-11e9-8fd2-fb28778ea9b2.png">

"edited" -- can you fix spelling -- maybe hot fix?

Actually let's say "edited by"

## How to test

Review change on test.elmcip.net

**Comment by steinmb** [comment]
commit 8f578edc6daba7c6ea7148675e23cd5aef5cb345 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Jan 29 16:33:30 2020 +0100

    Issue 432 Fix typo in View content_by_contributor

**Comment by elmcip** [comment]
Fixed.
