### ISSUE TITLE
Year data is missing from data export of works cited on critical writing pages

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#433]
<img width="776" alt="Screenshot 2019-09-26 16 21 50" src="https://user-images.githubusercontent.com/5831053/65696702-0077e480-e07a-11e9-8a83-f28156fd8738.png">
<img width="1345" alt="Screenshot 2019-09-26 16 17 55" src="https://user-images.githubusercontent.com/5831053/65696705-02da3e80-e07a-11e9-913a-7ebcaea48df0.png">

**Comment by elmcip** [comment]
The view is works_referenced_data -- would be useful to have the year data there.

**Comment by steinmb** [comment]
How does this look?


# Before change

<code>

Title | Title Nid | Author | Author ID | Year | Language | Tags | Tag ID
-- | -- | -- | -- | -- | -- | -- | --
Finnegan's Wake | 13832 | James Joyce | 13825 |   | English | modernism, avant garde, experimental literature | 2000320, 20005907, 20001424
The Waste Land | 13835 | Thomas Stearns Eliot | 13833 |   | English | modernism, poetry | 2000320, 200031
To the Lighthouse | 13842 | Virginia Woolf | 13836 |   | English | modernism, subjectivity, multiple focalization | 2000320, 2000491, 20008820
Mrs. Dalloway | 13844 | Virginia Woolf | 13836 |   | English | modernism, interiority | 2000320, 20008821
Ulysses | 13846 | James Joyce | 13825 |   | English | modernism, The Odyssey, intertextuality, stream-of-consciousness | 2000320, 20001723, 2000227, 20008822
The Life and Times of Tristram Shandy, Gentleman | 13851 | Laurence Sterne | 13847 |   | English | materiality, book as object, authorial intrusion | 200060, 20008823, 20008824
The Garden of Forking Paths | 7938 | Jorge Luis Borges | 7635 |   | English | infinite text, branching path, thriller, mystery | 20008825, 20002413, 20001507, 2000406
forking paths | 550 | Stuart Moulthrop | 351 |   | English | hypertext, intertextuality, pastiche, adaptation | 200039, 2000227, 2000307, 2000308
Victory Garden | 352 | Stuart Moulthrop | 351 |   | English | hypertext, fiction, war, politics, multilinear, map, Gulf War, spatial navigation | 200039, 200071, 20001231, 2000742, 2000824, 20002441, 20008826, 20008827
Rayuela / Hopscotch | 7895 | Julio Cortazar | 7894 |   |   | codex, chapters, multilinear, stream-of-consciousness | 20002141, 20004027, 2000824, 20008822
Composition No. 1 | 2060 | Marc Saporta | 2058 |   | French | nonlinear fiction, cybertext, artist book | 2000645, 200043, 20001484
Composition No. 1 | 2221 | Marc Saporta | 2058 |   | English | app, artist book, cybertext, nonlinear fiction, narrative | 20001485, 20001484, 200043, 2000645, 200013
VE3 Composition No. 1 | 2220 | Marc Saporta | 2058 |   | English | nonlinear fiction, artifact, cybertext, artist book | 2000645, 20001483, 200043, 20001484
The Unfortunates | 7836 | B. S. Johnson | 7835 |   | English | print, loose leaf, novel, narrative, non-linear, shuffle | 20001163, 20004005, 2000160, 200013, 20001784, 20008828
The Babysitter | 8138 | Robert Coover | 359 |   | English | fiction, print, multilinear, fantasy, postmodernism | 200071, 20001163, 2000824, 2000715, 2000711
Pricksongs and Descants | 13853 | Robert Coover | 359 |   |   | postmodernism, fiction, fairytales, intertextuality | 2000711, 200071, 20008829, 2000227
Sexing the Cherry | 13856 | Jeanette Winterson | 13854 |   |   | intertextuality, postmodernism, feminism | 2000227, 2000711, 2000716
Breakfast of Champions | 13859 | Kurt Vonnegut | 13857 |   | English | intertextuality, diegesis, postmodernism | 2000227, 20006327, 2000711
Nio | 817 | Jim Andrews | 778 |   | English | animation, audio, music, Shockwave, textual instrument, combinatorial, QuickTime, documentary | 200022, 2000306, 2000351, 2000390, 2000391, 2000458, 2000603, 2000419
Project for Tachistoscope [Bottomless Pit] | 1406 | William Poundstone | 649 |   | English | audio, time-based, image, essay/creative non-fiction, subliminal, iconography, concrete poetry, avant-garde,             narrative, visualization, media | 2000306, 2000602, 2000696, 2000982, 20001031, 20001032, 200016, 2000641, 200013, 2000626, 2000917
</code>

# After update

<code>

Title | Title Nid | Author | Author ID | Year | Language | Tags | Tag ID
-- | -- | -- | -- | -- | -- | -- | --
Finnegan's Wake | 13832 | James Joyce | 13825 | 1939 | English | modernism, avant garde, experimental literature | 2000320, 20005907, 20001424
The Waste Land | 13835 | Thomas Stearns Eliot | 13833 | 1922 | English | modernism, poetry | 2000320, 200031
To the Lighthouse | 13842 | Virginia Woolf | 13836 | 1910 | English | modernism, subjectivity, multiple focalization | 2000320, 2000491, 20008820
Mrs. Dalloway | 13844 | Virginia Woolf | 13836 | 1925 | English | modernism, interiority | 2000320, 20008821
Ulysses | 13846 | James Joyce | 13825 | 1922 | English | modernism, The Odyssey, intertextuality, stream-of-consciousness | 2000320, 20001723, 2000227, 20008822
The Life and Times of Tristram Shandy, Gentleman | 13851 | Laurence Sterne | 13847 | 1759 | English | materiality, book as object, authorial intrusion | 200060, 20008823, 20008824
The Garden of Forking Paths | 7938 | Jorge Luis Borges | 7635 | 1941 | English | infinite text, branching path, thriller, mystery | 20008825, 20002413, 20001507, 2000406
forking paths | 550 | Stuart Moulthrop | 351 | 1987 | English | hypertext, intertextuality, pastiche, adaptation | 200039, 2000227, 2000307, 2000308
Victory Garden | 352 | Stuart Moulthrop | 351 | 1991 | English | hypertext, fiction, war, politics, multilinear, map, Gulf War, spatial navigation | 200039, 200071, 20001231, 2000742, 2000824, 20002441, 20008826, 20008827
Rayuela / Hopscotch | 7895 | Julio Cortazar | 7894 | 1963 |   | codex, chapters, multilinear, stream-of-consciousness | 20002141, 20004027, 2000824, 20008822
Composition No. 1 | 2060 | Marc Saporta | 2058 | 1961 | French | nonlinear fiction, cybertext, artist book | 2000645, 200043, 20001484
Composition No. 1 | 2221 | Marc Saporta | 2058 | 2011 | English | app, artist book, cybertext, nonlinear fiction, narrative | 20001485, 20001484, 200043, 2000645, 200013
VE3 Composition No. 1 | 2220 | Marc Saporta | 2058 | 2011 | English | nonlinear fiction, artifact, cybertext, artist book | 2000645, 20001483, 200043, 20001484
The Unfortunates | 7836 | B. S. Johnson | 7835 | 1969 | English | print, loose leaf, novel, narrative, non-linear, shuffle | 20001163, 20004005, 2000160, 200013, 20001784, 20008828
The Babysitter | 8138 | Robert Coover | 359 | 1969 | English | fiction, print, multilinear, fantasy, postmodernism | 200071, 20001163, 2000824, 2000715, 2000711
Pricksongs and Descants | 13853 | Robert Coover | 359 | 1969 |   | postmodernism, fiction, fairytales, intertextuality | 2000711, 200071, 20008829, 2000227
Sexing the Cherry | 13856 | Jeanette Winterson | 13854 | 1989 |   | intertextuality, postmodernism, feminism | 2000227, 2000711, 2000716
Breakfast of Champions | 13859 | Kurt Vonnegut | 13857 | 1973 | English | intertextuality, diegesis, postmodernism | 2000227, 20006327, 2000711
Nio | 817 | Jim Andrews | 778 | 2001 | English | animation, audio, music, Shockwave, textual instrument, combinatorial, QuickTime, documentary | 200022, 2000306, 2000351, 2000390, 2000391, 2000458, 2000603, 2000419
Project for Tachistoscope [Bottomless Pit] | 1406 | William Poundstone | 649 | 2005 | English | audio, time-based, image, essay/creative non-fiction, subliminal, iconography, concrete poetry, avant-garde,             narrative, visualization, media | 2000306, 2000602, 2000696, 2000982, 20001031, 20001032, 200016, 2000641, 200013, 2000626, 2000917


</code

**Comment by elmcip** [comment]
That's what we wanted.
