### ISSUE TITLE
Review permissions for Library tags

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#434]
I just want to do a check in on what roles the "Not approved by Library" and "Approved by Library" tags appear too. I think that the "Not approved by Library" labels should only show up for Library and administrators.

Given the fact that we are only going to have librarians approving records slowly over time, we should not have most of our records labeled in a negative way that suggests that the data there is somehow not good.

**Comment by elmcip** [comment]
Though as I'm looking at it logged out, I don't see it, which is good. I just want to see a list of what roles see the librarian tools.

**Comment by hannahackermans** [comment]
@elmcip, I think we solved this with the new library record status. Do you still need this or can we close the issue?

**Comment by steinmb** [comment]
I think it is OK as it is now. Closing
