### ISSUE TITLE
problem in xls export with works with multiple languages

### ISSUE THREAD

**Issue by hannahackermans** [elmcip/elmcip#436]
Hi @steinmb , there is something weird going on in the Language and Language ID in export when there are several languages for a work. I think there is a comma missing and it just pastes all the id-number in a row to form one big number. This also means that the expanded export does not put multiple languages on different rows. 

## How to test/review

* Export data with multiple language entries from this [Creative work filtered page](https://test.elmcip.net/work?title_2=&title_3=Super+Mario+Bros&field_language_tax_tid=All&field_work_year_value_op=between&field_work_year_value%5Bvalue%5D%5Bdate%5D=&field_work_year_value%5Bmin%5D%5Bdate%5D=1985&field_work_year_value%5Bmax%5D%5Bdate%5D=1985&title=&title_4=&title_1=&taxonomy_vocabulary_1_tid=)

![Screenshot 2019-10-11 13 26 25](https://user-images.githubusercontent.com/18713442/66648043-ce928080-ec2a-11e9-925c-fecd90b13ca5.png)

**Comment by steinmb** [comment]
Thanks for taking the time splitting out these tasks. I'll have a look. I personally also think we should tackle part of issue #357 in here. Aka, make sure the data export is CVS.

Here is only changing the format, not anything else.

```
The Data Souls,15204,David Thomas Henry Wright,13309,2019,Blender,10285,"","","","","","","data narrative, frame narrative, kinetic","4869, 5359, 149"
Psychometric Researches,15203,Benjamin Laird,11960,2019,"","",Red Room Poetry,15201,English,20001636,Poetry Object,15202,"born-digital poetics, 3d image","6152, 6016"
AVATAR/MOCAP,15193,Alan Sondheim,1357,2016,"","","","","","",Electronic Literature Organization 2016: Next Horizons,11325,"",""
Just for the cameras,15192,Flourish Klink,3597,"","","","","","","",Electronic Literature Organization 2016: Next Horizons,11325,fan fiction,1901
Super Mario Bros,15107,Shigeru Miyamoto,14850,1985,Nintendo Entertainment System (NES),12828,Nintendo ,11689,English,20001636,"","","platform, nintendo, video game","2640, 5108, 1128"
Super Mario Bros,15107,Shigeru Miyamoto,14850,1985,Nintendo Entertainment System (NES),12828,Nintendo ,11689,Ewe,20007186,"","","platform, nintendo, video game","2640, 5108, 1128"
Super Mario Bros,15107,Shigeru Miyamoto,14850,1985,Nintendo Entertainment System (NES),12828,Nintendo ,11689,Japanese,20001649,"","","platform, nintendo, video game","2640, 5108, 1128"
Tetris,15106,"","",1984,Gameboy,10279,"","",English,20001636,"","","arcade, video game, puzzle","9411, 1128, 4510"
Tetris,15106,"","",1984,Gameboy,10279,"","",Ewe,20007186,"","","arcade, video game, puzzle","9411, 1128, 4510"
Tetris,15106,"","",1984,Commodore 64,10277,"","",English,20001636,"","","arcade, video game, puzzle","9411, 1128, 4510"
Tetris,15106,"","",1984,Commodore 64,10277,"","",Ewe,20007186,"","","arcade, video game, puzzle","9411, 1128, 4510"
Pac-Man,15103,"","",1980,Nintendo Entertainment System (NES),12828,"","",English,20001636,"","","arcade, arcade game, atari, video game","9411, 5034, 4494, 1128"
Pac-Man,15103,"","",1980,Nintendo Entertainment System (NES),12828,"","",Ewe,20007186,"","","arcade, arcade game, atari, video game","9411, 5034, 4494, 1128"
Pac-Man,15103,"","",1980,Atari,10329,"","",English,20001636,"","","arcade, arcade game, atari, video game","9411, 5034, 4494, 1128"
Pac-Man,15103,"","",1980,Atari,10329,"","",Ewe,20007186,"","","arcade, arcade game, atari, video game","9411, 5034, 4494, 1128"
Pac-Man,15103,"","",1980,Apple 2,10312,"","",English,20001636,"","","arcade, arcade game, atari, video game","9411, 5034, 4494, 1128"
Pac-Man,15103,"","",1980,Apple 2,10312,"","",Ewe,20007186,"","","arcade, arcade game, atari, video game","9411, 5034, 4494, 1128"
Pac-Man,15103,"","",1980,Gameboy,10279,"","",English,20001636,"","","arcade, arcade game, atari, video game","9411, 5034, 4494, 1128"
Pac-Man,15103,"","",1980,Gameboy,10279,"","",Ewe,20007186,"","","arcade, arcade game, atari, video game","9411, 5034, 4494, 1128"
Pac-Man,15103,"","",1980,Commodore 64,10277,"","",English,20001636,"","","arcade, arcade game, atari, video game","9411, 5034, 4494, 1128"
```

**Comment by steinmb** [comment]
Do the data export need a header? I have gone ahead and added headers to the rows. 

I have also improved the naming of the file generated from it uses this format `creative_work_<day>.<month>.<year>-<hour>.<minutes><seconds>.cvs`
Example: `creative_work_04.09.2020-15.14.10.csv` This to avoid that the browser need to keep renaming/overwrite the file.

```
"Title","Nid","Author","Author ID","Year","Platform/Software","Platform ID","Publisher","Publisher ID","Language","Language ID","Presented at Event","Event ID","Tags","Tags ID"
"Super Mario Bros","15107","Shigeru Miyamoto","14850","1985","Nintendo Entertainment System (NES)","12828","Nintendo ","11689","English","20001636","","","platform, nintendo, video game","2640, 5108, 1128"
"Super Mario Bros","15107","Shigeru Miyamoto","14850","1985","Nintendo Entertainment System (NES)","12828","Nintendo ","11689","Japanese","20001649","","","platform, nintendo, video game","2640, 5108, 1128"
"Super Mario Bros","15107","Shigeru Miyamoto","14850","1985","Nintendo Entertainment System (NES)","12828","Nintendo ","11689","Ewe","20007186","","","platform, nintendo, video game","2640, 5108, 1128"
```

**Comment by MagnusKnustad** [comment]
The same title shows up as different rows, one row for each language. Is that what we want?

![bilde](https://user-images.githubusercontent.com/59966448/92995500-877cd180-f504-11ea-981b-64648954f637.png)

**Comment by hannahackermans** [comment]
It shows up differently on my computer. All the information is in one cell rather than separated in different columns. Any ideas what happened here? Is it because we changed the extension?

<img width="932" alt="Screenshot 2020-09-16 11 52 50" src="https://user-images.githubusercontent.com/18713442/93322214-5c9bc180-f813-11ea-9a22-6804ac7385ba.png">

Apart from that, I think the expanded data export works well now. That's where we want all different information to be separated on different rows because it makes it much easier to prepare the nodes and edges for Gephi analysis. However, for the not-expanded view, we do not need them to be in  separate rows, I think. Side Question: that do people use the non-expanded data export and why?

**Comment by steinmb** [comment]
>It shows up differently on my computer.

Remember when you test that we have two different exports. Test both and compare:

1. https://test.elmcip.net/work/%2A/export?title_2=&title_3=Super%20Mario%20Bros&field_language_tax_tid=All&field_work_year_value_op=between&field_work_year_value%5Bvalue%5D%5Bdate%5D=&field_work_year_value%5Bmin%5D%5Bdate%5D=1985&field_work_year_value%5Bmax%5D%5Bdate%5D=1985&title=&title_4=&title_1=&taxonomy_vocabulary_1_tid=
1. https://test.elmcip.net/work/%2A/export2?title_2=&title_3=Super%20Mario%20Bros&field_language_tax_tid=All&field_work_year_value_op=between&field_work_year_value%5Bvalue%5D%5Bdate%5D=&field_work_year_value%5Bmin%5D%5Bdate%5D=1985&field_work_year_value%5Bmax%5D%5Bdate%5D=1985&title=&title_4=&title_1=&taxonomy_vocabulary_1_tid=

**Comment by jilltxt** [comment]
@hannahackermans Your data looks like a comma-separates CSV file that was opened as a regular spreadsheet instead of being imported as a csv - could that be why happened?

**Comment by steinmb** [comment]
Consider this fixed, closing.
