### ISSUE TITLE
Add "Brown Digital Repository entry" field

### ISSUE THREAD

**Issue by hannahackermans** [elmcip/elmcip#437]
In the Documentation tab of Creative Works, we need to add the field "Brown Digital Repository entry" to reference to works that are in BDR.  
The field help text should be "If there is a record for this work in the Brown Digital Repository, enter the URL of the entry." 

Two small decisions need to be made: 
1) The name "Brown Digital Repository" in the field help text should link to the BDR. Should the hyperlink be the general link to the whole of BDR, or to the search function of Digital Language Arts? https://repository.library.brown.edu/studio/search/?selected_facets=ir_collection_name%3ADigital+Language+Arts&search_field=
I vote for the second one as person clicking on it will be looking for a work specifically and the general BDR is quite big.
2) We have two types of fields for entering URLs to different databases and repositories: 
the first on is a field where you can only add one link, such as Electronic Literature Directory entry  and NT2. The second on allows you to "add another item". Which one will be most useful for BDR?

## How to test

* Test field on https://test.elmcip.net

![Screenshot 2019-12-09 09 53 00](https://user-images.githubusercontent.com/18713442/70421272-cc517480-1a69-11ea-8fd6-5d7e6a7d4480.png)

**Comment by steinmb** [comment]
>We have two types of fields for entering URLs to different databases and repositories:
the first on is a field where you can only add one link, such as Electronic Literature Directory entry and NT2. The second on allows you to "add another item". Which one will be most useful for BDR?

That is the cardinality (number of entries allowed) of the field. Same type of field. If there is only one brown entry and I guess it is, we should make sure they are only allowed to enter one?

**Comment by steinmb** [comment]
While I wait for feedback. Here is what we currently got. Anything that we need to change here?

![Screen Shot 2020-01-29 at 16 09 18](https://user-images.githubusercontent.com/683617/73368998-350edd80-42b2-11ea-8ad1-26a0ff6b5aec.png)

![Screen Shot 2020-01-29 at 16 10 10](https://user-images.githubusercontent.com/683617/73368997-350edd80-42b2-11ea-883c-e4dac8972cba.png)

**Comment by steinmb** [comment]
commit 343b639ce58cf6d73c6f5d82ad5879cd44744cb5 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Jan 29 16:19:08 2020 +0100

    Issue 437 New field Brown Digital Repository entry

    Name: field_brown_digital_repository

**Comment by elmcip** [comment]
We should make all of these labels clearer. Basically, I think we can change all the label texts for records in other databases to **"See also record in:"**

**Comment by steinmb** [comment]
Please let us address that in a separate issue. We have a lot of link fields in many content types. Let's try an keep the issue scope as narrow as possible.

**Comment by steinmb** [comment]
Nothing left here. Closing issue.
