### ISSUE TITLE
ELMCIP down for some days--Norstore again?

### ISSUE THREAD

**Issue by AlvaroSeica** [elmcip/elmcip#438]

**Comment by elmcip** [comment]
Yep— very irritating. Supposed to be back tomorrow but we shall see.

****
Typed on phone with thumbs. Forgive brevity, typos and autocorrects.

**Comment by steinmb** [comment]
## NIRD scheduled maintenance

We seems to be moved from Tromsø to the Trondheim infrastructure. We had to change the DNS information for the sites but yes we have been up to day. Spent a few hours on Friday making sure all services was working as expected.

* https://opslog.sigma2.no/2020/01/10/nird-and-nird-toolkit-scheduled-maintenance/
* https://elmcip.net - Up
* https://test.elmcip.net - Up
* https://anthology.elmcip.net - Up
* Local shell connection to test.elmcip.net through port 80 is not working yet. Give us a 401.
