### ISSUE TITLE
Remove outdated book pages and split out book config and permissions

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#441]
Book pages allow us to `create and organize related content in an outline` Used many years ago but was never kept up to date with the development and changes of the site. Popped up working on issue #439.

Content should be given a quick look through for hidden gems, delete node, and then split out config and permissions allowing us to drop it from elmcip.net as it no longer needed.

## Scope

* [x] Look through book content https://elmcip.net/admin/content - book pages and copy out if there is anything useful and then remove the node. Moved to https://github.com/elmcip/elmcip/blob/master/doc/book.md
* [x] Have a look at https://elmcip.net/book that is other types of content used to create books.
* [x] Split out config and permissions setting allowing us to drop functionality.
* [ ] Disable and uninstall book after release, remove tracked permissions.

## How to test

Nothing to test.

**Comment by steinmb** [comment]
commit 5788669fa30d39f44523f939d1a27ddb7bceda1c (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Oct 2 10:50:02 2019 +0200

    Issue 441 New feature module used by the feature module

commit 9ff76e775be24523b5ead6ab3ee3cce34560d4e1
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Oct 2 10:28:28 2019 +0200

    Issue 441 Move book module settings to separate module

    Allow installations that not need it to disable it.

**Comment by steinmb** [comment]
commit f9ed413009a6ce3867a253dc0e56abf906483519 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Tue Jan 28 12:02:52 2020 +0100

    Issue 441 Move old book nodes from production.

**Comment by steinmb** [comment]
None of these should have been used in a book - Have taken them out of the books. Administrator permission give a user permission to add TOC and book pages out of content types that should not use it.

![Screen Shot 2020-01-28 at 13 08 57](https://user-images.githubusercontent.com/683617/73263371-b726d580-41d0-11ea-9c84-155843db7559.png)

Only one left. Old data that look corrupt. TOC claiming it have book pages, there is none. Orphan, crash, bug. Not sure. Digging through the data structure in development. Stand bye.

**Comment by steinmb** [comment]
Node `https://elmcip.net/node/8491` incorrectly had `has_children` defined. This block book module from removing the book. Checked the db. and menu tree `book-toc-8491` and confirm that the book has ho children.

Found a workaround. Created a new notebook node that also define a new book entity. Moved 
the violating book to a book page of this. This trigger https://api.drupal.org/api/drupal/modules%21book%21book.module/function/book_update_bid/7.x and also validate and check if the item have any menu children. The node can no be removed from the book and test book can safely be removed. Puh!

**Comment by steinmb** [comment]
Looking good in dev. There is one left task in issue that we need to address after this release is out.

**Comment by elmcip** [comment]
We can just keep the data here in case we need it. At some point we should do a user's guide as a PDF but I think we can just re-pull all the help texts.

**Comment by steinmb** [comment]
commit bea88c41bf487f3fa13b09521efb631ead3c0cb0 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Feb 3 12:46:55 2020 +0100

    Issue 441 Remove book permissions
