### ISSUE TITLE
Lexical mistake with 'librarians'. Appears on the #445 issue

### ISSUE THREAD

**Issue by Antikrista** [elmcip/elmcip#447]
Important to take attention to the word 'librarian' solving the #445 issue.
This is an attentional place - we have to correct it. Later we will collect and provide to edit all of them.
Maybe can administrators correct lexical, grammar mistakes on their own?

<img width="1006" alt="Screenshot 2020-02-05 at 18 09 54" src="https://user-images.githubusercontent.com/58079572/73865204-3193cd00-4843-11ea-8890-44c2d413723e.png">

**Comment by steinmb** [comment]
Thanks for noticing. The flag system is getting removed and we do not need this issue any more. Closing
