### ISSUE TITLE
Replace librarian Flag system with a regular field

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#453]
Spin out from issue #394. The flagging system initially idea was that librarian could click through and approve records (Critical Writing and Creative Work) without editing the node and forcing the system to touch the last updated timestamp that we use to sort last edited record. After a year of use and discussions we have concluded to replace it:

* Librarians turned out to not need two states but at least three. Binary flagging states is not sufficient.
* Librarians edit the records anyway. The last updated is not a issue after all.
* Out of the box, the Flag module permission system is rather inflexible. We want to control what users that can see the state, who can approve, who can revoke –state.
* Proven hard to position flags status in node form. Main use is thought as a flag on node view.

## Suggested solution

* Content types: `creative work` and `critical working`
* ~~Remove Flag and all custom permissions and exported permissions and config.~~ Moved to issue #457
* Use a field with multiple states, values, also see issue #445 
* Get permissions just right, issue #444.

## How to test

* Test at https://test.elmcip.net
* Creative work, ciritical writing - Review/add/remove librarian status found in `Editorial Status`
* Field is found in `Editorial status` (issue #445)
* Review that permission is right (issue #444). Librarian can change it, admin and administrative groups can view data
* Tool to review and compare with the flag based system is as it always have been https://test.elmcip.net/knowledgebase/library_status - Filters and data exposure have been extended.

## History

@hannahackermans wrote:
>Simply question: Can you make it so that I can give people a librarian role when adding people? Librarian is not currently one of the options for me, which means I also cannot test how it is working with a test account.
    Difficult question: Currently every single record says "Not approved by librarian" simply because Adriana has not approved the records yet. The text suggests that the librarian actively disapproved the record. Would is be possible to differentiate 3 options:

   > if the record has not been reviewed by the librarian there is no text (or "not yet reviewed by librarian")
    if the record is reviewed and disapproved, the text "Not approved by librarian"
    if the record is reviewed and approved, the text "approved by librarian"
    I realize this is a difficult question because the first two both has 'off' on the toggle, but I think we need to find a solution for this. As a temporary band-aid, it might be better if we only show the text "approved by librarian", and no text in the other two. But eventually, we need to differentiate the three because we would want to improve records that are disapproved by librarian.

**Comment by steinmb** [comment]
@hannahackermans did not find the issue so I went ahead and created on Aud is not here. Does she not have a account? Difficult to communicate with here in issues if we can not include her. Do you know?

**Comment by audgjersdal** [comment]
I am here now

**Comment by elmcip** [comment]
This works for the temporary solution where both systems stay in place until the data is taken over to the new field. Hannah will do this manually once the release rolls.

**Comment by steinmb** [comment]
Lets tackle that in issue #461 - Closing
