### ISSUE TITLE
Data export button for Books (PhD Dissertations) is missing

### ISSUE THREAD

**Issue by jilltxt** [elmcip/elmcip#459]
The DIKULT207 students are adding records to update our collection of PhD dissertations, and in two weeks we need to export the data so they can start playing with it in Gephi. I am pretty sure that this view of all [Book (PhD Dissertations)](https://elmcip.net/category/publication-type/book-dissertation) used to have an XLS export button, but now it doesn't. Is it possible to add this? Probably the view exists from when I did the last round of dissertation visualisations in 2013/2014, but it's just no longer linked from the overview page?

We need the following fields:

- Node ID
- Author surname
- Year
- Title (of the dissertation)
- Tags
(could include University as well but not so important)

Here is what I need for Gephi (ignore column D, that is generated by Gephi, and add tags!)

<img width="740" alt="Screen Shot 2020-09-18 at 11 11 06" src="https://user-images.githubusercontent.com/44365847/93580184-b6c98d80-f99f-11ea-856d-555dfc8d1726.png">

Looks like the other data export function we need is already there: to make the edges from dissertations to creative works they cite, we need to export the works from each dissertation. Last time I think I did that manually by exporting from each dissertation entry (like from this one: https://elmcip.net/critical-writing/digital-literary-arts-scandinavian-e-texts-criticism-theory-and-practice) and copy-and-pasting them all into a big Excel file. Unless there is a simpler way to do this now, we'll do that again.

**Comment by steinmb** [comment]
> I am pretty sure that this view of all Book (PhD Dissertations) used to have an XLS export button, but now it doesn't.

No, we have never had any export from view by tag pages.

But anyway, [This page](https://test.elmcip.net/critical_writing?field_language_tax_tid=All&field_pubtype_tax_tid=1592&field_record_status_tax_tid=All&title=) is that not what you are looking for? It can export data.

**Comment by jilltxt** [comment]
That page looks perfect! Except I still can't see an export button?

**Comment by steinmb** [comment]
You need to be logged in

**Comment by jilltxt** [comment]
Brilliant, the XLS button is [there](https://elmcip.net/critical_writing?field_language_tax_tid=All&field_pubtype_tax_tid=1592&field_record_status_tax_tid=All&title=). Thank you!! I'll close the issue - a relief that it wasn't harder than that!! Have a great weekend!
