### ISSUE TITLE
Manually copy librarian status to new field

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#461]
Issue #453 introduced a new way to setting the librarian record status. There is not more than about 200 records not really enough to write data migration code.

## Scope

https://elmcip.net/knowledgebase/library_status and copy the data to new field.

**Comment by hannahackermans** [comment]
I have filled in the new status for all records that were library approved in the old flagging system. 
There were 4 records I had questions about, I will contact Aud about that now. I've copied the links for those, so as far as I'm concerned, we can remove the old system now.

**Comment by steinmb** [comment]
Good job! Feel free to close this when you feel you are done. This enable me to start working on issue #457.
