### ISSUE TITLE
Create site footer menu(s)

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#465]
To reduce the visual size of the header during redisign of it some of the menu links will be moved to a new page region if the page footer. Visible on all site pages.

## Scope of work

* [x] Test  out if a single menu or multiple menus are best.
* [x] Create custom menu block hosting site log and link to site front page.
* [x] Visual styling and positioning.

![Screenshot 2020-12-21 at 16 29 09](https://user-images.githubusercontent.com/683617/102793098-b3341100-43a9-11eb-9382-d56ab29bee94.png)

**Comment by steinmb** [comment]
commit 262b0d4a35761e90a5f45080dd2a8966674807f4 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Dec 21 16:05:20 2020 +0100

    Issue 465 Introduce horizontal green ELMCIP border

commit 37d7ee7d4ddbe4b54f2cee74e2ad43369dac034d
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Dec 21 14:47:56 2020 +0100

    Issue 465 Position footer blocks

commit 47570a247a92556442fa666ab13dbe4e4c3b26f6
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Dec 18 17:20:24 2020 +0100

    Issue 465 Use new text only logo

commit 8545193b2b61d5ba358c209011b1f1b14564e3af
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Dec 18 17:14:24 2020 +0100

    Issue 465 Custom site logo linking back to site front page.

**Comment by steinmb** [comment]
@LucilaM Have a look

**Comment by steinmb** [comment]
@LucilaM a quick look tell me there is a small bug in the footer that position/size of the ELMCIP svg. It have a different size in Safari and perhaps Chrome. We also need testing in Microsoft Edge and Internet Explorer 11.

**Comment by LucilaM** [comment]
yes, the only one which is looking good so far is the firefox one

**Comment by LucilaM** [comment]
yep, not looking good in chrome either

**Comment by LucilaM** [comment]
I will try edge and explorer in an emulator

**Comment by LucilaM** [comment]
In a very old emulator of Internet explorer works fine, but not in edge.

**Comment by steinmb** [comment]
This might improve Chrome and Safari. Take it for a spin.


commit 236d5bcee8ce91a45d88adda6e362009323fb314 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Dec 21 17:04:11 2020 +0100

    Issue 465 Prevent SVG logo in footer overflowing parent container

**Comment by LucilaM** [comment]
it works in all now!!!! could it be smaller maybe?

**Comment by LucilaM** [comment]
I've added a few links there and they are working, it seems that we can remove some of the links in the header soon, as they are duplicated now.
