### ISSUE TITLE
Improve ORCID form validation and perhaps use a custom field formatter

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#467]
@AlvaroSeica wrote: 
>We need to look into the ORCiD field again. Either we update the descrption txt to highlight that the full URL needs to be inserted, or we allow for insertion of the ID-only code with target https://orcid.org/ + code.
>
>I have noticed that if only the ID is inserted, the target is generated as https://elmcip.net/ + code (ERROR)

?See image below (https://elmcip.net/node/10200/edit)

<img width="655" alt="Captura de ecrã 2021-05-27, às 15 31 54" src="https://user-images.githubusercontent.com/6121438/119835079-cb7ffd00-bf00-11eb-8f64-82f6afa622be.png">

<img width="387" alt="Captura de ecrã 2021-05-27, às 15 32 14" src="https://user-images.githubusercontent.com/6121438/119835099-d0dd4780-bf00-11eb-9a59-c3f726ee80b4.png">

_Originally posted by @AlvaroSeica in https://github.com/elmcip/elmcip/issues/374#issuecomment-849638648_

**Comment by AlvaroSeica** [comment]
I'd perhaps go for both, to prevent errors: 
1. If inserting ID, target URL is corrected to:  <a href="https://orcid.org/[+ID]" target="_blank">ORCID</a> 
2. Allow for the full URL as well in the field
What do you think?

**Comment by steinmb** [comment]
ELMCIP have its own custom `Digital Object Identifier` field formatter. Time revisit that code I think.

**Comment by steinmb** [comment]
Confirm this is a bug. Have to retest the DOI field formatter. It even check to make sure the DOI string only contain the number. Viewing the node it render the DOI code with the URL hardcoded. Well, it is suppose to do that. Good catch.

**Comment by steinmb** [comment]
Strike that. We only have a custom validator for DOI, ORCID get no special treatment and by doing so we allow both full URL and numeric values to be used. I think that was why we decided to treat DOI with a custom formatter.

**Comment by steinmb** [comment]
Re-tested field. For ORCID we use the [Link](https://www.drupal.org/project/link) module. I would claim that the URL validation it provide is not working as expected, allowing this mix to me added.

![Screenshot 2021-06-09 at 13 08 41](https://user-images.githubusercontent.com/683617/121344269-db95d480-c923-11eb-8bbe-ef82fe1ca035.png)

We might have to roll our own custom code for this.

**Comment by AlvaroSeica** [comment]
OK, thx @steinmb so should we correct the text description to tell users they should insert only the full ORCID URL (to avoid the link error)?

**Comment by steinmb** [comment]
We should, but one other hand, we cannot trust the user to do the right thing here. In theory the Link module should have validated the data entered and rejected non URL text, but it does not.

I have pondered a bit on this. In https://github.com/elmcip/elmcip/commit/2885d07e5d295291cee9cf6294fb175a27cbf507 is there some work in progress.

**Comment by AlvaroSeica** [comment]
I see. Line 35 seems to be the golden coin:    return l($url, 'https://orcid.org/' . $url);
Let me know when you need testing

**Comment by steinmb** [comment]
Pushed the following changes to test.elmcip.net - Needs to be tested though:

commit b6cc2124d7b94969e00f6ade4c7acbfa64138bb2 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Jun 9 15:20:55 2021 +0200

    Issue 467 Improve ORCID validation and render

    Valid data is: full URL or the ORCID id.

commit cc4797c9f27b20409170725d94925330934391e9 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Jun 9 17:53:28 2021 +0200

    Issue 467 Update link settings with custom formatter and validator.

**Comment by AlvaroSeica** [comment]
Great, it works in both instances: ID code insertion and full URL
