### ISSUE TITLE
Add field for ELO's The NEXT to creative work and critical writing

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip#468]
We should add a field like those we have for the ELD, I love epoetry etc. for cross references to ELO's The NEXT: https://the-next.eliterature.org/

They are adding a bunch of records, so it would be good to get the field in place quickly.

## Content types

* Creative work
* Critical writing

## Permission

* Auth. users can add/edit/remove.
* Anon. users can view.

## How to test

Go to https://test.elmcip.net

* Add Next to creative work
* Add Next to critical writing
* Make sure forms is placed where expected
* Make sure Next link is placed where expected viewing node.

**Comment by steinmb** [comment]
@elmcip only in creative work?

**Comment by elmcip** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by elmcip** [comment]
Or no — I guess also critical writing.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by steinmb** [comment]
First commit. When find time take it for a spin at teste.elmcip.net. We also need to change Drupal 9 migration, making sure we migrate these data.

commit 73c2f33fa7143a4163693c56ff099a3cd8522be5 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Tue Jun 8 15:16:33 2021 +0200

    Issue 468 Add field for ELO's The NEXT

     Added to creative work and critical writing.
     https://the-next.eliterature.org/

**Comment by steinmb** [comment]
Looks OK to me
